const words4 = [
  { word: "ACID", clue: "A sour substance" },
  { word: "AGED", clue: "Grown old" },
  { word: "ALSO", clue: "In addition" },
  { word: "AREA", clue: "A region or part of a town" },
  { word: "ARMY", clue: "A large organized military force" },
  { word: "AWAY", clue: "To or at a distance" },
  { word: "BABY", clue: "A very young child" },
  { word: "BACK", clue: "The rear surface of the human body" },
  { word: "BALL", clue: "A solid or hollow spherical object" },
  { word: "BAND", clue: "A small group of musicians" },
  { word: "BANK", clue: "A financial establishment" },
  { word: "BASE", clue: "The lowest part or edge of something" },
  { word: "BATH", clue: "An act of washing the whole body" },
  { word: "BEAR", clue: "A large, heavy mammal" },
  { word: "BEAT", clue: "Strike (a person or an animal) repeatedly" },
  { word: "BEER", clue: "An alcoholic drink" },
  { word: "BELL", clue: "A hollow metal object that sounds a clear musical note" },
  { word: "BELT", clue: "A strip of leather or other material worn around the waist" },
  { word: "BEND", clue: "Shape or force (something straight) into a curve or angle" },
  { word: "BEST", clue: "Of the most excellent or desirable type or quality" },
  { word: "BILL", clue: "A printed or written statement of the money owed for goods or services" },
  { word: "BIRD", clue: "A warm-blooded egg-laying vertebrate" },
  { word: "BITE", clue: "(of a person or animal) use the teeth to cut into something" },
  { word: "BLUE", clue: "Of a color intermediate between green and violet" },
  { word: "BOAT", clue: "A vessel for travel on water" },
  { word: "BODY", clue: "The physical structure of a person or an animal" },
  { word: "BOMB", clue: "A container filled with explosive or incendiary material" },
  { word: "BOND", clue: "A relationship between people or groups based on shared feelings, interests, or experiences" },
  { word: "BONE", clue: "Any of the pieces of hard, whitish tissue making up the skeleton in humans and other vertebrates" },
  { word: "BOOK", clue: "A written or printed work consisting of pages glued or sewn together along one side" },
  { word: "BORN", clue: "Existing as a result of birth" },
  { word: "BOSS", clue: "A person who is in charge of a worker or organization" },
  { word: "BOTH", clue: "Used to refer to two people or things, regarded and identified together" },
  { word: "BOWL", clue: "A round, deep dish or basin used for food or liquid" },
  { word: "BUSY", clue: "Having a great deal to do" },
  { word: "CALL", clue: "A cry made as a summons or to attract someone's attention" },
  { word: "CAMP", clue: "A place with temporary accommodations of huts, tents, or other structures" },
  { word: "CARD", clue: "A piece of thick, stiff paper or thin pasteboard" },
  { word: "CARE", clue: "The provision of what is necessary for the health, welfare, maintenance, and protection of someone or something" },
  { word: "CASE", clue: "An instance of a particular situation" },
  { word: "CASH", clue: "Money in coins or notes" },
  { word: "CAST", clue: "Cause (light or shadow) to appear on a surface" },
  { word: "CELL", clue: "A small room in which a prisoner is locked up" },
  { word: "CHAT", clue: "Talk in a friendly and informal way" },
  { word: "CHEF", clue: "A professional cook" },
  { word: "CHIP", clue: "A small piece of something removed in the course of chopping, cutting, or breaking something" },
  { word: "CITY", clue: "A large town" },
  { word: "CLUB", clue: "An association dedicated to a particular interest or activity" },
  { word: "COAL", clue: "A combustible black or dark brown rock" },
  { word: "COAT", clue: "An outer garment worn outdoors" },
  { word: "CODE", clue: "A system of words, letters, figures, or other symbols substituted for other words, letters, etc." },
  { word: "COIN", clue: "A flat, typically round piece of metal with an official stamp" },
  { word: "COLD", clue: "Of or at a low or relatively low temperature" },
  { word: "COME", clue: "Move or travel toward or into a place thought of as near or familiar to the speaker" },
  { word: "COOK", clue: "Prepare (food, a dish, or a meal) by combining and heating the ingredients in various ways" },
  { word: "COOL", clue: "Of or at a fairly low temperature" },
  { word: "COPY", clue: "A thing made to be similar or identical to another" },
  { word: "CORE", clue: "The tough central part of various fruits" },
  { word: "CORN", clue: "A tall annual cereal grass that yields large grains" },
  { word: "COST", clue: "(of an object or action) require the payment of (a specified sum of money) before it can be acquired or done" },
  { word: "CREW", clue: "A group of people who work on and operate a ship, aircraft, etc." },
  { word: "CROP", clue: "A cultivated plant that is grown as food" },
  { word: "DARK", clue: "With little or no light" },
  { word: "DATE", clue: "The day of the month or year as specified by a number" },
  { word: "DEAD", clue: "No longer alive" },
  { word: "DEAL", clue: "Distribute (cards) in an orderly rotation" },
  { word: "DEAR", clue: "Regarded with deep affection" },
  { word: "DEBT", clue: "A sum of money that is owed or due" },
  { word: "DEEP", clue: "Extending far down from the top or surface" },
  { word: "DEER", clue: "A hoofed grazing or browsing animal" },
  { word: "DESK", clue: "A piece of furniture with a flat table-style work surface" },
  { word: "DIAL", clue: "A movable marker on a measuring instrument" },
  { word: "DIET", clue: "The kinds of food that a person, animal, or community habitually eats" },
  { word: "DINE", clue: "Eat dinner" },
  { word: "DIRT", clue: "A substance, such as mud or dust, that soils someone or something" },
  { word: "DISH", clue: "A shallow, flat-bottomed container for cooking or serving food" },
  { word: "DOOR", clue: "A hinged, sliding, or revolving barrier at the entrance to a building, room, or vehicle" },
  { word: "DOWN", clue: "Toward or in a lower place or position" },
  { word: "DRAW", clue: "Produce (a picture or diagram) by making lines and marks on paper with a pencil, pen, etc." },
  { word: "DROP", clue: "Let or make (something) fall vertically" },
  { word: "DRUG", clue: "A medicine or other substance which has a physiological effect when ingested or otherwise introduced into the body" },
  { word: "DRUM", clue: "A percussion instrument sounded by being struck with sticks or the hands" },
  { word: "DUCK", clue: "A waterfowl with a broad blunt bill, short legs, webbed feet, and a waddling gait" },
  { word: "DUST", clue: "Fine, dry powder consisting of tiny particles of earth or waste matter lying on the ground or on surfaces or carried in the air" },
  { word: "DUTY", clue: "A moral or legal obligation; a responsibility" },
  { word: "EACH", clue: "Used to refer to every one of two or more people or things, regarded and identified separately" },
  { word: "EARL", clue: "A British nobleman ranking above a viscount and below a marquess" },
  { word: "EARN", clue: "Obtain money in return for labor or services" },
  { word: "EAST", clue: "The direction toward the point of the horizon where the sun rises at the equinoxes" },
  { word: "EASY", clue: "Achieved without great effort; presenting few difficulties" },
  { word: "EDGE", clue: "The outside limit of an object, area, or surface" },
  { word: "ELSE", clue: "In addition; besides" },
  { word: "EVEN", clue: "Flat and smooth" },
  { word: "EVER", clue: "At all times; always" },
  { word: "FACE", clue: "The front part of a person's head from the forehead to the chin" },
  { word: "FACT", clue: "A thing that is known or proved to be true" },
  { word: "FAIL", clue: "Be unsuccessful in achieving one's goal" },
  { word: "FAIR", clue: "In accordance with the rules or standards; legitimate" },
  { word: "FALL", clue: "Move downward, typically rapidly and freely without control, from a higher to a lower level" },
  { word: "FARM", clue: "An area of land and its buildings used for growing crops and rearing animals" },
  { word: "FAST", clue: "Moving or capable of moving at high speed" },
  { word: "FATE", clue: "The development of events beyond a person's control, regarded as determined by a supernatural power" },
  { word: "FEAR", clue: "An unpleasant emotion caused by the belief that someone or something is dangerous, likely to cause pain, or a threat" },
  { word: "FEED", clue: "Give food to" },
  { word: "FEEL", clue: "Be aware of (a person or object) through touching or being touched" },
  { word: "FEET", clue: "The lower extremity of the leg below the ankle" },
  { word: "FELL", clue: "Past of fall" },
  { word: "FILE", clue: "A folder or box for holding loose papers that are typically arranged in a particular order for easy reference" },
  { word: "FILL", clue: "Cause (a space or container) to become full or almost full" },
  { word: "FILM", clue: "A thin flexible strip of plastic or other material coated with light-sensitive emulsion for exposure in a camera" },
  { word: "FIND", clue: "Discover or perceive by chance or unexpectedly" },
  { word: "FINE", clue: "Of high quality" },
  { word: "FIRE", clue: "Combustion or burning, in which substances combine chemically with oxygen from the air and typically give out bright light, heat, and smoke" },
  { word: "FIRM", clue: "Having a solid, almost unyielding surface or structure" },
  { word: "FISH", clue: "A limbless cold-blooded vertebrate animal with gills and fins and living wholly in water" },
  { word: "FIVE", clue: "Equivalent to the sum of two and three; one more than four" },
  { word: "FLAT", clue: "Having a level surface; without raised areas or indentations" },
  { word: "FLOW", clue: "(of a liquid, gas, or electricity) move along or out steadily and continuously in a current or stream" },
  { word: "FOOD", clue: "Any nutritious substance that people or animals eat or drink" },
  { word: "FOOT", clue: "The lower extremity of the leg below the ankle" },
  { word: "FORM", clue: "The visible shape or configuration of something" },
  { word: "FORT", clue: "A fortified building or strategic position" },
  { word: "FOUR", clue: "Equivalent to the sum of two and two; one more than three" },
  { word: "FREE", clue: "Able to act or be done as one wishes; not under the control of another" },
  { word: "FROG", clue: "A tailless amphibian with a short-squat body, moist smooth skin, and very long hind legs for leaping" },
  { word: "FROM", clue: "Indicating the point in space at which a journey, motion, or action starts" },
  { word: "FUEL", clue: "Material such as coal, gas, or oil that is burned to produce heat or power" },
  { word: "FULL", clue: "Containing or holding as much or as many as possible; having no empty space" },
  { word: "FUND", clue: "A sum of money saved or made available for a particular purpose" },
  { word: "GAME", clue: "An activity that one engages in for amusement or fun" },
  { word: "GATE", clue: "A hinged barrier used to close an opening in a wall, fence, or hedge" },
  { word: "GEAR", clue: "The machinery in a vehicle that turns engine power into movement" },
  { word: "GENE", clue: "A unit of heredity which is transferred from a parent to offspring and is held to determine some characteristic of the offspring" },
  { word: "GIFT", clue: "A thing given willingly to someone without payment; a present" },
  { word: "GIRL", clue: "A female child or young woman" },
  { word: "GIVE", clue: "Freely transfer the possession of something to someone" },
  { word: "GLAD", clue: "Pleased; delighted" },
  { word: "GLOW", clue: "Give out steady light without flame" },
  { word: "GOAL", clue: "A pair of posts linked by a crossbar" },
  { word: "GODS", clue: "Beings with supernatural powers or attributes" },
  { word: "GOLD", clue: "A yellow precious metal" },
  { word: "GOLF", clue: "A game played on a large open-air course" },
  { word: "GOOD", clue: "To be desired or approved of" },
  { word: "GRAY", clue: "Of a color intermediate between black and white" },
  { word: "GREY", clue: "Another spelling of gray" },
  { word: "GROW", clue: "Undergo natural development by increasing in size" },
  { word: "HAIR", clue: "Fine threadlike strands growing from the skin" },
  { word: "HALF", clue: "One of two equal parts" },
  { word: "HALL", clue: "The room just inside the front entrance of a house" },
  { word: "HAND", clue: "The end part of a person's arm" },
  { word: "HANG", clue: "Suspend from above with the lower part dangling free" },
  { word: "HARD", clue: "Solid, firm, and rigid" },
  { word: "HARM", clue: "Physical injury" },
  { word: "HATE", clue: "Feel intense or passionate dislike for" },
  { word: "HAVE", clue: "Possess, own, or hold" },
  { word: "HEAD", clue: "The upper part of the human body" },
  { word: "HEAR", clue: "Perceive with the ear the sound made by something" },
  { word: "HEAT", clue: "The quality of being hot" },
  { word: "HEEL", clue: "The back part of the foot" },
  { word: "HELL", clue: "A place of punishment after death" },
  { word: "HELP", clue: "Make it easier for someone to do something" },
  { word: "HERB", clue: "A plant used for flavoring, food, or medicine" },
  { word: "HERE", clue: "In, at, or to this place or position" },
  { word: "HIGH", clue: "Of great vertical extent" },
  { word: "HILL", clue: "A naturally raised area of land, not as high as a mountain" },
  { word: "HIRE", clue: "Employ someone for wages" },
  { word: "HOLD", clue: "Grasp, carry, or support with one's arms or hands" },
  { word: "HOLE", clue: "A hollow place in a solid body or surface" },
  { word: "HOLY", clue: "Dedicated or consecrated to God" },
  { word: "HOME", clue: "The place where one lives permanently" },
  { word: "HOPE", clue: "A feeling of expectation and desire for a certain thing to happen" },
  { word: "HORN", clue: "A hard permanent outgrowth found on the heads of some animals" },
  { word: "HOUR", clue: "A period of time equal to a twenty-fourth part of a day" },
  { word: "HUGE", clue: "Extremely large; enormous" },
  { word: "HUNT", clue: "Pursue and kill a wild animal for sport or food" },
  { word: "HURT", clue: "Cause physical pain or injury to" },
  { word: "IDEA", clue: "A thought or suggestion" },
  { word: "INCH", clue: "A unit of linear measure" },
  { word: "INTO", clue: "Expressing movement with the result that something becomes enclosed" },
  { word: "IRON", clue: "A strong, hard magnetic silvery-gray metal" },
  { word: "ITEM", clue: "An individual article or unit" },
  { word: "JOIN", clue: "Link; connect" },
  { word: "JOKE", clue: "A thing that someone says to cause amusement" },
  { word: "JUMP", clue: "Push oneself off a surface and into the air" },
  { word: "JURY", clue: "A body of people sworn to give a verdict in a legal case" },
  { word: "JUST", clue: "Based on what is morally right and fair" },
  { word: "KEEP", clue: "Have or retain possession of" },
  { word: "KICK", clue: "Strike or propel forcibly with the foot" },
  { word: "KILL", clue: "Cause the death of a person, animal, or other living thing" },
  { word: "KIND", clue: "A class or type of people or things" },
  { word: "KING", clue: "The male ruler of an independent state" },
  { word: "KISS", clue: "Touch with the lips as a sign of love or greeting" },
  { word: "KNOW", clue: "Have knowledge or information about" },
  { word: "LACK", clue: "The state of being without something" },
  { word: "LADY", clue: "A woman" },
  { word: "LAKE", clue: "A large body of water surrounded by land" },
  { word: "LAMB", clue: "A young sheep" },
  { word: "LAND", clue: "The part of the earth's surface that is not covered by water" },
  { word: "LATE", clue: "Happening toward the end of a given period of time" },
  { word: "LEAD", clue: "Cause a person or animal to go with one by holding them by the hand, a halter, or a leash" },
  { word: "LEAK", clue: "A hole in a container through which contents accidentally escape" },
  { word: "LEAP", clue: "Jump or spring a long way, to a great height, or with great force" },
  { word: "LEFT", clue: "On, toward, or relating to the side of a human body or of a thing which is to the west when facing north" },
  { word: "LEGS", clue: "Each of the limbs on which a person or animal walks" },
  { word: "LESS", clue: "A smaller amount of" },
  { word: "LIFE", clue: "The condition that distinguishes living organisms from non-living things" },
  { word: "LIFT", clue: "Raise to a higher position or level" },
  { word: "LIKE", clue: "Having the same characteristics or qualities as" },
  { word: "LION", clue: "A large carnivorous feline" },
  { word: "LIST", clue: "A number of connected items or names written or printed consecutively" },
  { word: "LIVE", clue: "Have one's home in a particular place or with a particular person" },
  { word: "LOAD", clue: "A heavy or bulky thing that is being carried" },
  { word: "LOAN", clue: "A thing that is borrowed" },
  { word: "LOCK", clue: "A device for securing a door, lid, etc." },
  { word: "LONG", clue: "Measuring a great distance from end to end" },
  { word: "LOOK", clue: "Direct one's gaze toward something or someone or in a specified direction" },
  { word: "LORD", clue: "A master or ruler" },
  { word: "LOSE", clue: "Be deprived of or cease to have or retain (something)" },
  { word: "LOSS", clue: "The action or fact of losing or being lost" },
  { word: "LOST", clue: "Past of lose" },
  { word: "LOVE", clue: "An intense feeling of deep affection" },
  { word: "MADE", clue: "Past tense of make" },
  { word: "MAIL", clue: "Letters and parcels sent by post" },
  { word: "MAIN", clue: "Chief in size or importance" },
  { word: "MAKE", clue: "Form (something) by putting parts together" },
  { word: "MALE", clue: "Of or denoting the sex that produces gametes (sperm) typical of male" },
  { word: "MALL", clue: "A large building containing a variety of stores" },
  { word: "MANY", clue: "A large number of" },
  { word: "MARK", clue: "A small spot or stain on a surface" },
  { word: "MASS", clue: "A large body of matter with no definite shape" },
  { word: "MAZE", clue: "A network of paths designed as a puzzle" },
  { word: "MEAL", clue: "An occasion when food is eaten" },
  { word: "MEAN", clue: "Intend to convey, indicate, or refer to" },
  { word: "MEAT", clue: "The flesh of an animal as food" },
  { word: "MENU", clue: "A list of dishes available in a restaurant" },
  { word: "MICE", clue: "Plural of mouse" },
  { word: "MILE", clue: "A unit of distance equal to 1,760 yards" },
  { word: "MILK", clue: "An opaque white fluid rich in fat and protein" },
  { word: "MIND", clue: "The element of a person that enables them to be aware of the world" },
  { word: "MINE", clue: "A place from which minerals are extracted" },
  { word: "MORE", clue: "A greater or additional amount or degree" },
  { word: "MOST", clue: "Greatest in amount or degree" },
  { word: "MOVE", clue: "Go from one place to another" },
  { word: "MUCH", clue: "A great amount of" },
  { word: "MUSE", clue: "A person or personified force who is the source of inspiration for a creative artist" },
  { word: "MUST", clue: "Be obliged to; should" },
  { word: "MYTH", clue: "A widely held but false belief or idea" },
  { word: "NAIL", clue: "A small metal spike with a broadened flat head" },
  { word: "NAME", clue: "A word or set of words by which a person or thing is known" },
  { word: "NASH", clue: "A surname or place name" },
  { word: "NAVE", clue: "The main part of a church" },
  { word: "NAVY", clue: "The branch of a nation's armed forces that conducts military operations at sea" },
  { word: "NEAR", clue: "At, to, or by a short distance or time" },
  { word: "NECK", clue: "The part of a person's or animal's body connecting the head to the trunk" },
  { word: "NEED", clue: "Require (something) because it is essential" },
  { word: "NEWS", clue: "Information about recent events" },
  { word: "NEXT", clue: "Immediately following in time or order" },
  { word: "NICE", clue: "Pleasant; agreeable; satisfactory" },
  { word: "NINE", clue: "Equivalent to the sum of one and eight" },
  { word: "NONE", clue: "Not any" },
  { word: "NOON", clue: "Twelve o'clock in the middle of the day; midday" },
  { word: "NOSE", clue: "The part of the face or head through which an animal breathes and smells" },
  { word: "NOTE", clue: "A short written message or record" },
  { word: "NOUN", clue: "A word (other than a pronoun) used to identify any of a class of people, places, or things" },
  { word: "NOVEL", clue: "A fictitious prose narrative of book length" },
  { word: "NOWL", clue: "A word with a rare or obsolete spelling, also an owl" },
  { word: "NUTS", clue: "A fruit consisting of a hard shell and a kernel" },
  { word: "OATH", clue: "A solemn promise" },
  { word: "ODOR", clue: "A distinctive smell" },
  { word: "OHMS", clue: "A unit of electrical resistance" },
  { word: "OILY", clue: "Covered in or soaked with oil" },
  { word: "OKAY", clue: "In a satisfactory or good manner" },
  { word: "ONCE", clue: "On one occasion or for one time only" },
  { word: "ONLY", clue: "And nothing more besides" },
  { word: "ONTO", clue: "Moving to a position on the surface of" },
  { word: "OPEN", clue: "Not closed or barred" },
  { word: "ORAL", clue: "By word of mouth" },
  { word: "ORCA", clue: "A large toothed whale" },
  { word: "ORGY", clue: "A wild party" },
  { word: "OVEN", clue: "An enclosed compartment for cooking and heating" },
  { word: "OVER", clue: "Moving from one place or side to another" },
  { word: "OWED", clue: "Be in debt to" },
  { word: "OWLS", clue: "Nocturnal birds of prey" },
  { word: "PACE", clue: "A single step taken when walking or running" },
  { word: "PACK", clue: "A small cardboard or paper box and the contents it holds" },
  { word: "PAGE", clue: "One side of a sheet of paper in a book, magazine, etc." },
  { word: "PAID", clue: "Past tense of pay" },
  { word: "PAIN", clue: "Physical suffering or discomfort" },
  { word: "PAIR", clue: "A set of two things used together" },
  { word: "PALE", clue: "Light in color or shade" },
  { word: "PALM", clue: "The inner surface of the hand" },
  { word: "PAPA", clue: "A term for father" },
  { word: "PARK", clue: "A large public garden or area of land" },
  { word: "PART", clue: "A piece of a whole" },
  { word: "PASS", clue: "Move onward" },
  { word: "PAST", clue: "Gone by in time" },
  { word: "PATH", clue: "A route or track between two places" },
  { word: "PEAK", clue: "The pointed top of a mountain" },
  { word: "PEAR", clue: "A sweet juicy fruit" },
  { word: "PEAS", clue: "A small round green seed" },
  { word: "PEEL", clue: "The outer layer of a fruit or vegetable" },
  { word: "PEER", clue: "Look with difficulty or concentration" },
  { word: "PINE", clue: "An evergreen coniferous tree" },
  { word: "PINK", clue: "A pale reddish color" },
  { word: "PINT", clue: "A unit of liquid measurement" },
  { word: "PIPE", clue: "A tube through which a fluid can flow" },
  { word: "PITY", clue: "The feeling of sorrow and compassion" },
  { word: "PLAN", clue: "A detailed proposal for doing something" },
  { word: "PLAY", clue: "Engage in an activity for enjoyment" },
  { word: "PLOT", clue: "A secret plan or scheme" },
  { word: "PLUG", clue: "A device for connecting an electrical appliance to the mains" },
  { word: "PLUS", clue: "A sign indicating addition" },
  { word: "POEM", clue: "A piece of writing in which words are chosen for their sound and rhythm" },
  { word: "POET", clue: "A person who writes poems" },
  { word: "POLE", clue: "A long, slender, rounded piece of wood or metal" },
  { word: "POND", clue: "A small body of still water" },
  { word: "PONY", clue: "A horse of a small breed" },
  { word: "POOL", clue: "A small body of still water" },
  { word: "POOR", clue: "Lacking sufficient money to live comfortably" },
  { word: "POPE", clue: "The bishop of Rome" },
  { word: "PORK", clue: "Meat from a pig" },
  { word: "PORT", clue: "A town or city with a harbor" },
  { word: "POST", clue: "A long, sturdy piece of timber or metal set upright in the ground" },
  { word: "POUR", clue: "To flow rapidly in a steady stream" },
  { word: "PRAY", clue: "To address God with adoration" },
  { word: "PREY", clue: "An animal that is hunted and killed by another for food" },
  { word: "PULL", clue: "To exert force on so as to cause or tend to cause movement toward the force" },
  { word: "PULP", clue: "A soft, wet, shapeless mass of material" },
  { word: "PUMP", clue: "A mechanical device using suction or pressure" },
  { word: "PUNK", clue: "A loud, fast-moving, and aggressive form of rock music" },
  { word: "PURE", clue: "Not mixed or adulterated with any other substance or material" },
  { word: "PUSH", clue: "Exert force on (someone or something) in order to move them away" },
  { word: "PUTT", clue: "To strike a golf ball gently" },
  { word: "QUAD", clue: "A four-sided figure, especially a quadrilateral" },
  { word: "QUAY", clue: "A concrete, stone, or metal platform running alongside or projecting into water" },
  { word: "QUIT", clue: "To leave (a place)" },
  { word: "QUIZ", clue: "A test of knowledge" },
  { word: "RACE", clue: "A competition between runners, horses, vehicles, etc." },
  { word: "RACK", clue: "A framework, typically with bars, for holding things" },
  { word: "RAFT", clue: "A flat buoyant structure of logs, planks, or inflated pads" },
  { word: "RAGE", clue: "Violent uncontrollable anger" },
  { word: "RAID", clue: "A sudden attack on an enemy" },
  { word: "RAIL", clue: "A bar or series of bars, typically fixed on upright supports" },
  { word: "RAIN", clue: "Moisture condensed from the atmosphere that falls visibly in separate drops" },
  { word: "RAKE", clue: "A garden tool with a long handle and a row of teeth at the end" },
  { word: "RANK", clue: "A position in a hierarchy" },
  { word: "RARE", clue: "Not occurring very often" },
  { word: "RATE", clue: "A measure, quantity, or frequency" },
  { word: "READ", clue: "Look at and comprehend the meaning of (written or printed matter)" },
  { word: "REAL", clue: "Actually existing as a thing or occurring in fact" },
  { word: "REAR", clue: "The back part of something" },
  { word: "RENT", clue: "A tenant's regular payment to a landlord for the use of property" },
  { word: "REST", clue: "Cease work or movement" },
  { word: "RICE", clue: "A cereal grain that is a staple food for a large part of the world's population" },
  { word: "RICH", clue: "Having a great deal of money or assets" },
  { word: "RIDE", clue: "Sit on and control the movement of (an animal, typically a horse)" },
  { word: "RING", clue: "A small circular band, typically of precious metal, worn on a finger" },
  { word: "RISE", clue: "Move from a lower position to a higher one; come up" },
  { word: "RISK", clue: "A situation involving exposure to danger" },
  { word: "ROAD", clue: "A wide way leading from one place to another" },
  { word: "ROCK", clue: "The solid mineral material forming part of the surface of the earth" },
  { word: "RODE", clue: "Past tense of ride" },
  { word: "ROLE", clue: "An actor's part in a play" },
  { word: "ROLL", clue: "Move or cause to move by turning over and over on an axis" },
  { word: "ROOF", clue: "The structure forming the upper covering of a building or vehicle" },
  { word: "ROOM", clue: "A part of a building enclosed by walls" },
  { word: "ROOT", clue: "The part of a plant that attaches it to the ground or to a support" },
  { word: "ROPE", clue: "A length of twisted or braided strands of fiber or wire" },
  { word: "ROSE", clue: "A prickly bush or shrub that typically bears red, pink, yellow, or white fragrant flowers" },
  { word: "ROSY", clue: "Colored like a rose; pink or reddish" },
  { word: "ROTT", clue: "To undergo decay or decomposition" },
  { word: "ROVE", clue: "To travel without a fixed route" },
  { word: "RUDE", clue: "Offensive in an impolite or improper way" },
  { word: "RUFF", clue: "A common type of collar" },
  { word: "RUIN", clue: "The physical destruction or collapse of something" },
  { word: "RULE", clue: "One of a set of explicit or understood regulations or principles" },
  { word: "RUNG", clue: "Past participle of ring" },
  { word: "RUSH", clue: "To move with urgent haste" },
  { word: "SACK", clue: "A large bag made of coarse material" },
  { word: "SAFE", clue: "Protected from or not exposed to danger or risk" },
  { word: "SAID", clue: "Past tense of say" },
  { word: "SAIL", clue: "A piece of material extended on a mast to catch the wind" },
  { word: "SALE", clue: "The exchange of goods or services for money" },
  { word: "SALT", clue: "A white crystalline substance" },
  { word: "SAME", clue: "Identical; not different" },
  { word: "SAND", clue: "A loose granular substance" },
  { word: "SAVE", clue: "Keep safe or rescue from harm or danger" },
  { word: "SAYE", clue: "An obsolete spelling of say" },
  { word: "SEAL", clue: "A device or substance used to join two things together so as to prevent them from coming apart or to prevent liquid or gas from passing between them" },
  { word: "SEAM", clue: "A line where two pieces of fabric are sewn together" },
  { word: "SEAT", clue: "A thing made or used for sitting on" },
  { word: "SEEN", clue: "Past participle of see" },
  { word: "SELL", clue: "Give or hand over (something) in exchange for money" },
  { word: "SEND", clue: "Cause to go or be taken to a particular destination" },
  { word: "SETS", clue: "A group of things" },
  { word: "SHAD", clue: "A type of fish" },
  { word: "SHAG", clue: "A type of carpet" },
  { word: "SHIP", clue: "A large boat for transporting goods or people by sea" },
  { word: "SHOE", clue: "A covering for the foot" },
  { word: "SHOP", clue: "A place where goods are sold" },
  { word: "SHOT", clue: "The firing of a gun" },
  { word: "SHOW", clue: "A theatrical performance or a public display of things" },
  { word: "SHUT", clue: "Move (a door or window) so as to block its opening" },
  { word: "SICK", clue: "Feeling ill or unwell" },
  { word: "SIDE", clue: "A position to the left or right of an object" },
  { word: "SIGN", clue: "A gesture or movement used to convey information" },
  { word: "SING", clue: "To make musical sounds with the voice" },
  { word: "SINK", clue: "Go down below the surface of a liquid" },
  { word: "SIZE", clue: "The relative extent of something; its dimensions or magnitude" },
  { word: "SKIN", clue: "The thin layer of tissue forming the natural outer covering of the body of a person or animal" },
  { word: "SLAB", clue: "A large, thick, flat piece of stone or concrete" },
  { word: "SLAP", clue: "Strike (someone or something) with the palm of one's hand or a flat object" },
  { word: "SLAY", clue: "Kill (a person or animal) in a violent way" },
  { word: "SLIP", clue: "Lose one's footing and slide unintentionally for a short distance" },
  { word: "SLOW", clue: "Moving or operating at a low speed" },
  { word: "SMOG", clue: "Fog or haze intensified by smoke or other atmospheric pollutants" },
  { word: "SNAP", clue: "Break with a sharp crack" },
  { word: "SNOW", clue: "Atmospheric water vapor frozen into ice crystals" },
  { word: "SOAP", clue: "A substance used with water for washing and cleaning" },
  { word: "SOFA", clue: "A long upholstered seat with a back and arms" },
  { word: "SOFT", clue: "Easy to mold, cut, compress, or fold" },
  { word: "SOIL", clue: "The upper layer of earth in which plants grow" },
  { word: "SOLD", clue: "Past tense of sell" },
  { word: "SOME", clue: "An unspecified amount or number of" },
  { word: "SONG", clue: "A short poem or other set of words set to music" },
  { word: "SOON", clue: "In or after a short time" },
  { word: "SORT", clue: "A category of things having some properties in common" },
  { word: "SOUL", clue: "The spiritual or immaterial part of a human being or animal" },
  { word: "SOUP", clue: "A liquid food made by boiling meat, fish, or vegetables" },
  { word: "SOUR", clue: "Having an acidic taste like that of vinegar or lemons" },
  { word: "SPIN", clue: "Turn or cause to turn or whirl around quickly" },
  { word: "SPOT", clue: "A small round or roundish mark" },
  { word: "STAR", clue: "A sphere of plasma held together by its own gravity" },
  { word: "STAY", clue: "Remain in the same place" },
  { word: "STEP", clue: "An act of lifting and putting down one's foot" },
  { word: "STEM", clue: "The main body or stalk of a plant" },
  { word: "STOP", clue: "Come to an end" },
  { word: "STOW", clue: "Pack or store (an object) carefully and neatly in a particular place" },
  { word: "SUCH", clue: "Of the type already mentioned or implied" },
  { word: "SURE", clue: "Certainly" },
  { word: "SWAN", clue: "A large water bird" },
  { word: "SWIM", clue: "Propel the body through water" },
  { word: "TALK", clue: "To speak in order to give information or express ideas" },
  { word: "TALL", clue: "Of great or more than average height" },
  { word: "TANK", clue: "A large container for holding liquid or gas" },
  { word: "TAPE", clue: "A long, narrow strip of fabric or plastic material" },
  { word: "TASK", clue: "A piece of work to be done or undertaken" },
  { word: "TAXI", clue: "A car available for hire" },
  { word: "TEAM", clue: "A group of players forming one side in a competitive game" },
  { word: "TEAR", clue: "Rip or pull (something) apart or to pieces" },
  { word: "TENT", clue: "A portable shelter consisting of canvas" },
  { word: "TERM", clue: "A word or phrase used to describe a thing or to express a concept" },
  { word: "TEST", clue: "A procedure intended to establish the quality, performance, or reliability of something" },
  { word: "TEXT", clue: "A book or other written or printed work" },
  { word: "THAN", clue: "Introducing the second element in a comparison" },
  { word: "THAT", clue: "Used to refer to a person or thing" },
  { word: "THEY", clue: "Used to refer to two or more people or things" },
  { word: "THIN", clue: "Having a small distance between opposite sides or surfaces" },
  { word: "THIS", clue: "Used to refer to a person, animal, or thing that is present or near" },
  { word: "TIDE", clue: "The alternate rising and falling of the sea" },
  { word: "TILE", clue: "A thin slab of concrete or earthenware" },
  { word: "TIME", clue: "The indefinite continued progress of existence and events" },
  { word: "TINY", clue: "Extremely small" },
  { word: "TOAD", clue: "A tailless amphibian" },
  { word: "TOLD", clue: "Past tense of tell" },
  { word: "TONE", clue: "A musical or vocal sound" },
  { word: "TORN", clue: "Past participle of tear" },
  { word: "TOUR", clue: "A journey for pleasure in which several different places are visited" },
  { word: "TOWN", clue: "A built-up area with a name, and generally a specific political status" },
  { word: "TOYS", clue: "An object for a child to play with" },
  { word: "TRAY", clue: "A flat receptacle with a raised rim" },
  { word: "TREE", clue: "A woody perennial plant" },
  { word: "TREK", clue: "A long arduous journey" },
  { word: "TRUE", clue: "In accordance with fact or reality" },
  { word: "TURN", clue: "Move in a circular direction wholly or partly around an axis or point" },
  { word: "TWOO", clue: "A word meaning 'two' but with an unusual spelling" },
  { word: "UGLY", clue: "Unpleasant or repulsive" },
  { word: "UNDO", clue: "Unfasten or unwrap" },
  { word: "UNIT", clue: "A single thing or person" },
  { word: "UPON", clue: "On" },
  { word: "URGE", clue: "A strong desire or impulse" },
  { word: "USED", clue: "Having already been used" },
  { word: "USER", clue: "A person who uses a product, service, or system" },
  { word: "VERY", clue: "In a high degree; extremely" },
  { word: "VIEW", clue: "The ability to see something or to be seen from a particular place" },
  { word: "VOTE", clue: "A formal expression of opinion or choice" },
  { word: "WAIT", clue: "Stay where one is or delay action until a particular time or event" },
  { word: "WAKE", clue: "Emerge or cause to emerge from a state of sleep" },
  { word: "WALK", clue: "Move at a regular and fairly slow pace by lifting and setting down each foot in turn" },
  { word: "WALL", clue: "A continuous vertical brick or stone structure that encloses or divides an area of land" },
  { word: "WANT", clue: "Have a desire to possess or do (something); wish for" },
  { word: "WARM", clue: "Of or at a fairly high temperature" },
  { word: "WASH", clue: "Clean with water and soap" },
  { word: "WASP", clue: "A stinging winged insect" },
  { word: "WATCH", clue: "Look at or observe attentively over a period of time" },
  { word: "WAVE", clue: "A long body of water curling into an arched form and breaking on the shore" },
  { word: "WEAR", clue: "Have (something) on one's body as clothing" },
  { word: "WEEK", clue: "A period of seven days" },
  { word: "WELL", clue: "In a good or satisfactory way" },
  { word: "WENT", clue: "Past tense of go" },
  { word: "WERE", clue: "Past tense of be" },
  { word: "WEST", clue: "The direction toward the point of the horizon where the sun sets" },
  { word: "WHAT", clue: "Asking for information" },
  { word: "WHEN", clue: "At what time" },
  { word: "WHEY", clue: "The watery part of milk" },
  { word: "WIFE", clue: "A married woman" },
  { word: "WILD", clue: "Living or growing in a natural state" },
  { word: "WILL", clue: "Expressing a future intention" },
  { word: "WIND", clue: "The natural movement of the air" },
  { word: "WINE", clue: "An alcoholic drink made from fermented grape juice" },
  { word: "WING", clue: "A part of an animal that is used for flying" },
  { word: "WISH", clue: "A desire or hope for something to happen" },
  { word: "WITH", clue: "Accompanied by" },
  { word: "WORD", clue: "A single distinct meaningful element of speech or writing" },
  { word: "WORK", clue: "Activity involving mental or physical effort done in order to achieve a purpose or result" },
  { word: "WORM", clue: "A soft-bodied invertebrate" },
  { word: "YARD", clue: "A unit of length equal to 3 feet" },
  { word: "YEAR", clue: "The time taken by the earth to make one revolution around the sun" },
  { word: "YOGA", clue: "A Hindu spiritual and ascetic discipline" },
  { word: "YOUR", clue: "Belonging to or associated with the person or people that the speaker is addressing" },
  { word: "ZERO", clue: "The number 0" },
  { word: "ZONE", clue: "An area or region distinguished from adjacent parts by a particular characteristic or use" }
];