
const words = [
  { word: "Aba", clue: "A loose sleeveless outer garment worn by Arabs." },
  { word: "Abs", clue: "Abdominal muscles (short form)." },
  { word: "Ace", clue: "A playing card with a single spot." },
  { word: "Act", clue: "To do something." },
  { word: "Add", clue: "To join something to something else." },
  { word: "Ado", clue: "A state of agitation or fuss." },
  { word: "Ads", clue: "Advertisements (short form)." },
  { word: "Aft", clue: "At, near, or towards the stern of a ship or tail of an aircraft." },
  { word: "Age", clue: "The length of time that a person has lived or a thing has existed." },
  { word: "Ago", clue: "Before the present; in the past." },
  { word: "Aha", clue: "Used to express satisfaction, triumph, or surprise." },
  { word: "Aid", clue: "Help, typically of a practical nature." },
  { word: "Ail", clue: "Trouble or afflict in mind or body." },
  { word: "Aim", clue: "Point or direct (a weapon or camera) at a target." },
  { word: "Air", clue: "The invisible gaseous substance surrounding the earth." },
  { word: "Ale", clue: "A type of beer with a bitter flavour and high alcoholic content." },
  { word: "All", clue: "Used to refer to the whole quantity or extent of a particular group or thing." },
  { word: "Alp", clue: "A high mountain." },
  { word: "Alt", clue: "The key on a computer keyboard that is used to change the function of other keys." },
  { word: "Ama", clue: "A Japanese diver, especially a woman, who collects seaweed, shellfish, or pearls." },
  { word: "Ami", clue: "A friend, especially a male friend." },
  { word: "Amp", clue: "An amplifier, especially one for an electric guitar." },
  { word: "Ana", clue: "A collection of miscellaneous information about a particular subject." },
  { word: "And", clue: "Used to connect words of the same part of speech, clauses, or sentences that are to be taken jointly." },
  { word: "Ani", clue: "A tropical American black cuckoo." },
  { word: "Ant", clue: "A small insect typically living in a complex social colony." },
  { word: "Any", clue: "Used to refer to one or some of a thing or number of things, no matter how much or many." },
  { word: "Ape", clue: "A large primate that lacks a tail, including the gorilla, chimpanzees, orangutan, and gibbons." },
  { word: "App", clue: "An application, especially as downloaded by a user to a mobile device." },
  { word: "Apt", clue: "Appropriate or suitable in the circumstances." },
  { word: "Arc", clue: "A part of the circumference of a circle or other curve." },
  { word: "Are", clue: "Second person singular present and first, second, third person plural present of 'to be'." },
  { word: "Ark", clue: "The ship built by Noah in which he, his family, and the animals were saved from the Flood." },
  { word: "Arm", clue: "Each of the two upper limbs of the human body from the shoulder to the hand." },
  { word: "Art", clue: "The expression or application of human creative skill and imagination." },
  { word: "Ash", clue: "The powdery residue left after the burning of a substance." },
  { word: "Ask", clue: "Say something in order to obtain an answer or some information." },
  { word: "Asp", clue: "A small venomous snake of North Africa and southwestern Asia." },
  { word: "Ass", clue: "A hoofed mammal of the horse family with long ears and a braying call." },
  { word: "Ate", clue: "Past of 'eat'." },
  { word: "Ava", clue: "An aromatic plant of the pepper family, native to the Pacific islands." },
  { word: "Ave", clue: "An avenue." },
  { word: "Awa", clue: "A New Zealand marine fish with a bluish-green back and silvery-white belly." },
  { word: "Awe", clue: "A feeling of reverential respect mixed with fear or wonder." },
  { word: "Awl", clue: "A small pointed tool used for piercing holes, especially in leather." },
  { word: "Aye", clue: "Yes." },
  { word: "Bad", clue: "Of poor quality or a low standard." },
  { word: "Bag", clue: "A flexible container with an opening at the top, used for carrying things." },
  { word: "Bah", clue: "An expression of contempt or disgust." },
  { word: "Bam", clue: "A sudden loud noise." },
  { word: "Ban", clue: "Officially or legally prohibit." },
  { word: "Bap", clue: "A large, soft, floury bread roll." },
  { word: "Bar", clue: "A long rigid piece of wood, metal, or similar material, used as an obstruction, fastening, or weapon." },
  { word: "Bat", clue: "An implement with a handle and a solid surface, used for hitting a ball in games." },
  { word: "Bay", clue: "A broad inlet of the sea where the land curves inwards." },
  { word: "Bed", clue: "A piece of furniture used for sleep or rest." },
  { word: "Bee", clue: "A stinging winged insect that collects nectar and pollen." },
  { word: "Beg", clue: "Ask for something, typically food or money, as charity or a gift." },
  { word: "Bel", clue: "A unit of sound intensity, equal to ten decibels." },
  { word: "Ben", clue: "The inner room or parlour of a two-roomed cottage." },
  { word: "Bet", clue: "Risk a sum of money or valued item against someone else's on the basis of the outcome of an unpredictable event." },
  { word: "Bey", clue: "The governor of a district or province in the Ottoman Empire." },
  { word: "Bib", clue: "A piece of cloth or plastic fastened round a child's neck to keep its clothes clean while eating." },
  { word: "Bid", clue: "Offer a certain price for something, especially at an auction." },
  { word: "Big", clue: "Of considerable size, extent, or intensity." },
  { word: "Bin", clue: "A receptacle for storing a specified substance." },
  { word: "Bio", clue: "A biography or short biographical profile of someone." },
  { word: "Bit", clue: "A small piece, part, or quantity of something." },
  { word: "Biz", clue: "Business." },
  { word: "Boa", clue: "A long, thin decorative scarf or stole made of feathers or fur." },
  { word: "Bob", clue: "Make a quick, short movement up and down." },
  { word: "Bod", clue: "A body." },
  { word: "Bog", clue: "An area of wet muddy ground that is too soft to support a heavy body." },
  { word: "Boo", clue: "A sound made to express contempt or disapproval." },
  { word: "Bop", clue: "Dance to pop music." },
  { word: "Bot", clue: "The larva of the botfly, which is a parasite of horses." },
  { word: "Bow", clue: "A knot tied with two loops and two loose ends." },
  { word: "Box", clue: "A container with a flat base and sides, typically square or rectangular and having a lid." },
  { word: "Boy", clue: "A male child or young man." },
  { word: "Bra", clue: "An undergarment worn by women to support the breasts." },
  { word: "Bro", clue: "A brother." },
  { word: "Bub", clue: "Used as a familiar form of address to a man or boy." },
  { word: "Bud", clue: "A compact knob-like growth on a plant that develops into a leaf, flower, or shoot." },
  { word: "Bug", clue: "A small insect." },
  { word: "Bum", clue: "A person who avoids work and sponges on others." },
  { word: "Bun", clue: "A small cake, typically containing currants." },
  { word: "Bur", clue: "A prickly seed case or flower head that clings to clothing and animal fur." },
  { word: "Bus", clue: "A large motor vehicle carrying passengers by road." },
  { word: "But", clue: "Used to introduce a phrase or clause contrasting with what has already been mentioned." },
  { word: "Buy", clue: "Obtain in exchange for payment." },
  { word: "Bye", clue: "The transfer of a competitor directly to the next round of a competition in the absence of an assigned opponent." },
  { word: "Cab", clue: "A taxi." },
  { word: "Cad", clue: "A man who behaves dishonourably, especially towards a woman." },
  { word: "Cam", clue: "A projecting part of a rotating wheel or shaft that strikes a lever at one or more points on its circular path." },
  { word: "Can", clue: "A cylindrical metal container." },
  { word: "Cap", clue: "A kind of soft, flat hat, typically with a peak." },
  { word: "Car", clue: "A road vehicle, typically with four wheels, powered by an internal combustion engine or electric motor and able to carry a small number of people." },
  { word: "Cat", clue: "A small domesticated carnivorous mammal with soft fur, a short snout, and retractable claws." },
  { word: "Caw", clue: "The harsh cry of a rook, crow, or raven." },
  { word: "Cay", clue: "A low bank or reef of coral, rock, or sand." },
  { word: "Cee", clue: "The letter C." },
  { word: "Cel", clue: "A transparent sheet of celluloid or similar plastic on which objects are drawn or painted for traditional hand-drawn animation." },
  { word: "Cha", clue: "Tea." },
  { word: "Che", clue: "Used as a familiar form of address, especially in Argentina." },
  { word: "Chi", clue: "The twenty-second letter of the Greek alphabet." },
  { word: "Cig", clue: "A cigarette." },
  { word: "Cob", clue: "The central, cylindrical, woody part of the maize ear, to which the grains are attached." },
  { word: "Cod", clue: "A large marine fish with a small barbel on the chin." },
  { word: "Cog", clue: "A wheel or bar with a series of projections on its edge that transfers motion by engaging with projections on another wheel or bar." },
  { word: "Col", clue: "A depression in the ridge of a range of mountains." },
  { word: "Con", clue: "Persuade someone to do or believe something by lying to them." },
  { word: "Coo", clue: "The characteristic soft, murmuring sound made by a pigeon or dove." },
  { word: "Cop", clue: "A police officer." },
  { word: "Cor", clue: "Used to express surprise, admiration, or alarm." },
  { word: "Cos", clue: "A kind of lettuce with crisp, elongated leaves." },
  { word: "Cot", clue: "A child's bed with high, barred sides." },
  { word: "Cow", clue: "A fully grown female animal of a domesticated breed of ox, kept to produce milk or beef." },
  { word: "Cox", clue: "A coxswain of a racing boat." },
  { word: "Coy", clue: "Making a pretence of shyness or modesty that is intended to be alluring." },
  { word: "Coz", clue: "A cousin." },
  { word: "Cru", clue: "A vineyard or group of vineyards, especially one of recognized quality." },
  { word: "Cry", clue: "Shed tears, typically as an expression of distress, pain, or sorrow." },
  { word: "Cub", clue: "The young of a fox, bear, lion, or other carnivorous mammal." },
  { word: "Cud", clue: "Partly digested food returned from the first stomach of ruminants to the mouth for further chewing." },
  { word: "Cue", clue: "A signal for action." },
  { word: "Cup", clue: "A small bowl-shaped container for drinking from, typically having a handle." },
  { word: "Cur", clue: "An aggressive dog or one that is in poor condition, especially a mongrel." },
  { word: "Cut", clue: "Make an opening, incision, or wound in (something) with a sharp-edged tool or object." },
  { word: "Dab", clue: "Press against (something) lightly with a piece of absorbent material in order to clean or dry it." },
  { word: "Dad", clue: "One's father." },
  { word: "Dag", clue: "A dirty or untidy person." },
  { word: "Dal", clue: "Split pulses, in particular lentils." },
  { word: "Dam", clue: "A barrier constructed to hold back water and raise its level, forming a reservoir used to generate electricity or as a water supply." },
  { word: "Dan", clue: "A level of expertise in a martial art, represented by a coloured belt." },
  { word: "Dap", clue: "Fish by letting the bait bob up and down on the surface of the water." },
  { word: "Daw", clue: "A jackdaw." },
  { word: "Day", clue: "Each of the twenty-four-hour periods, reckoned from one midnight to the next, into which a week, month, or year is divided." },
  { word: "Deb", clue: "A debutante." },
  { word: "Dee", clue: "The letter D." },
  { word: "Def", clue: "Excellent." },
  { word: "Del", clue: "A delegate." },
  { word: "Den", clue: "A wild mammal's hidden home; a lair." },
  { word: "Dev", clue: "A developer." },
  { word: "Dew", clue: "Tiny drops of water that form on cool surfaces at night, when atmospheric vapour condenses." },
  { word: "Dex", clue: "A tablet of dextroamphetamine sulphate." },
  { word: "Dib", clue: "A small, nondescript object." },
  { word: "Did", clue: "Past of 'do'." },
  { word: "Die", clue: "Stop living." },
  { word: "Dig", clue: "Break up and move earth with a tool or machine, or with hands, paws, snout, etc." },
  { word: "Dim", clue: "Not shining brightly or clearly." },
  { word: "Din", clue: "A loud, unpleasant, and prolonged noise." },
  { word: "Dip", clue: "Put or let something down quickly or briefly in or into liquid." },
  { word: "Dis", clue: "Speak disrespectfully to or criticize." },
  { word: "Doc", clue: "A doctor." },
  { word: "Doe", clue: "A female deer." },
  { word: "Dog", clue: "A domesticated carnivorous mammal that typically has a long snout, an acute sense of smell, and a barking, howling, or whining voice." },
  { word: "Doh", clue: "The first and last note of a major scale in sol-fa." },
  { word: "Dol", clue: "A unit of pain intensity." },
  { word: "Dom", clue: "A title prefixed to the names of some Roman Catholic dignitaries and monks of the Benedictine and other orders." },
  { word: "Don", clue: "A university teacher, especially a senior member of a college at Oxford or Cambridge." },
  { word: "Doo", clue: "A dove or pigeon." },
  { word: "Dop", clue: "A tot of brandy or other spirits." },
  { word: "Dor", clue: "A dung beetle." },
  { word: "Dos", clue: "The second note of a major scale in sol-fa." },
  { word: "Dot", clue: "A small round mark or spot." },
  { word: "Dow", clue: "The Dow Jones Industrial Average." },
  { word: "Dry", clue: "Free from moisture or liquid; not wet or moist." },
  { word: "Dub", clue: "Give an unofficial name or nickname to." },
  { word: "Dud", clue: "A thing that fails to work properly or is otherwise unsatisfactory or worthless." },
  { word: "Due", clue: "Expected at or planned for at a certain time." },
  { word: "Dug", clue: "Past and past participle of 'dig'." },
  { word: "Duh", clue: "Used to express disdainful comprehension of something obvious." },
  { word: "Dum", clue: "A stupid person." },
  { word: "Dun", clue: "Of a dull greyish-brown colour." },
  { word: "Duo", clue: "A pair of people or things, especially in music or entertainment." },
  { word: "Dup", clue: "A duplicate." },
  { word: "Dye", clue: "A substance used to add a colour to or change the colour of something." },
  { word: "Ear", clue: "The organ of hearing and balance in humans and other vertebrates." },
  { word: "Eat", clue: "Put food into the mouth and chew and swallow it." },
  { word: "Ebb", clue: "The movement of the tide out to sea." },
  { word: "Eco", clue: "Not harming the environment." },
  { word: "Ecu", clue: "A former European currency unit." },
  { word: "Eek", clue: "An exclamation of alarm or surprise." },
  { word: "Eel", clue: "A snakelike fish with a slender, elongated body and poorly developed fins, proverbial for its slipperiness." },
  { word: "Egg", clue: "An oval or round object laid by female birds, reptiles, amphibians, fish, and insects, containing the developing embryo." },
  { word: "Ego", clue: "A person's sense of self-esteem or self-importance." },
  { word: "Eke", clue: "Make an amount or supply of something last longer by using or consuming it frugally." },
  { word: "Elf", clue: "A supernatural creature of folk tales, typically represented as a small, delicate, elusive creature in human form with pointed ears, magical powers, and a capricious nature." },
  { word: "Elk", clue: "A large deer with palmate antlers, found in North America, Europe, and Asia." },
  { word: "Elm", clue: "A tall deciduous tree that has rough, serrated leaves and small, winged fruits." },
  { word: "Emu", clue: "A large flightless fast-running Australian bird resembling the ostrich, with shaggy grey or brown plumage, a long neck and legs, and three-toed feet." },
  { word: "End", clue: "A final part of something, especially a period of time, an activity, or a story." },
  { word: "Eng", clue: "The velar nasal, a letter of the Cyrillic and Latin alphabets, used in some languages to represent the ‘ng’ sound." },
  { word: "Ens", clue: "An existing or real thing; an entity." },
  { word: "Eon", clue: "An indefinite and very long period of time." },
  { word: "Era", clue: "A long and distinct period of history with a particular feature or characteristic." },
  { word: "Erg", clue: "A unit of work or energy, equal to the work done by a force of one dyne when its point of application moves one centimetre in the direction of the force." },
  { word: "Err", clue: "Be mistaken or incorrect; make a mistake." },
  { word: "Ess", clue: "The letter S." },
  { word: "Eta", clue: "The seventh letter of the Greek alphabet." },
  { word: "Eth", clue: "A letter in the Old English, Icelandic, and Faroese alphabets, representing a voiced dental fricative." },
  { word: "Eve", clue: "The day or period of time immediately before an event or occasion." },
  { word: "Ewe", clue: "A female sheep." },
  { word: "Eye", clue: "Each of a pair of globular organs in the head through which humans and vertebrate animals see." },
  { word: "Fab", clue: "Fabulous; wonderful." },
  { word: "Fad", clue: "An intense and widely shared enthusiasm for something, especially one that is short-lived; a craze." },
  { word: "Fag", clue: "A tiring or unwelcome task." },
  { word: "Fan", clue: "An apparatus with rotating blades that creates a current of air for cooling or ventilation." },
  { word: "Far", clue: "At, to, or by a great distance." },
  { word: "Fat", clue: "A natural oily or greasy substance occurring in animal bodies, especially when deposited as a layer under the skin or around certain organs." },
  { word: "Fax", clue: "An exact copy of a document made by electronic scanning and transmitted as data by telecommunications links." },
  { word: "Fay", clue: "A fairy." },
  { word: "Fed", clue: "Past and past participle of 'feed'." },
  { word: "Fee", clue: "A payment made to a professional person or to a professional or public body in exchange for advice or services." },
  { word: "Fem", clue: "A female." },
  { word: "Fen", clue: "A low and marshy or frequently flooded area of land." },
  { word: "Fer", clue: "For." },
  { word: "Fet", clue: "Fetch." },
  { word: "Few", clue: "A small number of." },
  { word: "Fey", clue: "Giving an impression of vague unworldliness." },
  { word: "Fez", clue: "A flat-topped conical red hat with a black tassel on top, worn by men in some Muslim countries." },
  { word: "Fib", clue: "A trivial lie." },
  { word: "Fid", clue: "A conical tool for splicing rope." },
  { word: "Fig", clue: "A soft, pear-shaped fruit with sweet, dark flesh and many small seeds, eaten fresh or dried." },
  { word: "Fil", clue: "A thread or filament." },
  { word: "Fin", clue: "A flattened appendage on various parts of the body of many aquatic vertebrates and some invertebrates, including fish and cetaceans, used for propelling, steering, and balancing." },
  { word: "Fir", clue: "An evergreen coniferous tree with upright cones and flat needle-shaped leaves." },
  { word: "Fit", clue: "Of a suitable quality, standard, or type to meet the required purpose." },
  { word: "Fix", clue: "Fasten (something) securely in a particular place or position." },
  { word: "Fiz", clue: "Fizz." },
  { word: "Flu", clue: "Influenza." },
  { word: "Fly", clue: "Move through the air using wings." },
  { word: "Fob", clue: "A chain attached to a watch for carrying in a waistcoat or waistband pocket." },
  { word: "Foe", clue: "An enemy or opponent." },
  { word: "Fog", clue: "A thick cloud of tiny water droplets suspended in the atmosphere at or near the earth's surface which obscures or restricts visibility." },
  { word: "Fon", clue: "The Fon language." },
  { word: "Fop", clue: "A man who is concerned with his clothes and appearance in an affected and excessive way." },
  { word: "For", clue: "In support of or in favour of (a person or policy)." },
  { word: "Fox", clue: "A carnivorous mammal of the dog family with a pointed snout and a bushy tail, proverbial for its cunning." },
  { word: "Foy", clue: "A farewell gift or party." },
  { word: "Fro", clue: "From." },
  { word: "Fry", clue: "Cook (food) in hot fat or oil, typically in a shallow pan." },
  { word: "Fub", clue: "To fob." },
  { word: "Fud", clue: "A stupid or foolish person." },
  { word: "Fug", clue: "A warm, stuffy, or smoky atmosphere in a room." },
  { word: "Fun", clue: "Enjoyment, amusement, or light-hearted pleasure." },
  { word: "Fur", clue: "The short, fine, soft hair of certain animals." }
];
