[
  {"word": "Aba", "clue": "Sleeveless Arab garment"},
  {"word": "Abs", "clue": "Abdominal muscles, briefly"},
  {"word": "Ace", "clue": "Top playing card"},
  {"word": "Act", "clue": "Perform or do"},
  {"word": "Add", "clue": "Sum up numbers"},
  {"word": "Ado", "clue": "Fuss or commotion"},
  {"word": "Ads", "clue": "Short for advertisements"},
  {"word": "Aft", "clue": "Rear of a ship"},
  {"word": "Age", "clue": "Length of existence"},
  {"word": "Ago", "clue": "In the past"},
  {"word": "Aha", "clue": "Cry of realization"},
  {"word": "Aid", "clue": "Provide help"},
  {"word": "Ail", "clue": "Feel unwell"},
  {"word": "Aim", "clue": "Target or goal"},
  {"word": "Air", "clue": "Earth's atmosphere"},
  {"word": "Ale", "clue": "Type of beer"},
  {"word": "All", "clue": "Entire amount"},
  {"word": "Alp", "clue": "High mountain"},
  {"word": "Alt", "clue": "Keyboard modifier key"},
  {"word": "Ama", "clue": "Japanese pearl diver"},
  {"word": "Ami", "clue": "Friend, in French"},
  {"word": "Amp", "clue": "Guitar sound booster"},
  {"word": "Ana", "clue": "Collection of miscellany"},
  {"word": "And", "clue": "Connecting word"},
  {"word": "Ani", "clue": "Tropical black cuckoo"},
  {"word": "Ant", "clue": "Social insect"},
  {"word": "Any", "clue": "Some or one"},
  {"word": "Ape", "clue": "Tailless primate"},
  {"word": "App", "clue": "Mobile device program"},
  {"word": "Apt", "clue": "Suitable or fitting"},
  {"word": "Arc", "clue": "Curved line segment"},
  {"word": "Are", "clue": "Form of 'to be'"},
  {"word": "Ark", "clue": "Noah's flood vessel"},
  {"word": "Arm", "clue": "Upper limb"},
  {"word": "Art", "clue": "Creative expression"},
  {"word": "Ash", "clue": "Burning residue"},
  {"word": "Ask", "clue": "Request information"},
  {"word": "Asp", "clue": "Venomous snake"},
  {"word": "Ass", "clue": "Donkey or fool"},
  {"word": "Ate", "clue": "Consumed food"},
  {"word": "Ava", "clue": "Pacific island plant"},
  {"word": "Ave", "clue": "Short for avenue"},
  {"word": "Awa", "clue": "New Zealand fish"},
  {"word": "Awe", "clue": "Wonder and respect"},
  {"word": "Awl", "clue": "Leather-piercing tool"},
  {"word": "Aye", "clue": "Affirmative vote"},
  {"word": "Bad", "clue": "Poor quality"},
  {"word": "Bag", "clue": "Flexible container"},
  {"word": "Bah", "clue": "Exclamation of disdain"},
  {"word": "Bam", "clue": "Loud impact sound"},
  {"word": "Ban", "clue": "Officially prohibit"},
  {"word": "Bap", "clue": "Soft bread roll"},
  {"word": "Bar", "clue": "Long rigid piece"},
  {"word": "Bat", "clue": "Baseball hitting tool"},
  {"word": "Bay", "clue": "Curved coastal inlet"},
  {"word": "Bed", "clue": "Furniture for sleep"},
  {"word": "Bee", "clue": "Nectar-collecting insect"},
  {"word": "Beg", "clue": "Plead for charity"},
  {"word": "Bel", "clue": "Sound intensity unit"},
  {"word": "Ben", "clue": "Scottish cottage room"},
  {"word": "Bet", "clue": "Wager on an outcome"},
  {"word": "Bey", "clue": "Ottoman governor"},
  {"word": "Bib", "clue": "Child's eating protector"},
  {"word": "Bid", "clue": "Offer at auction"},
  {"word": "Big", "clue": "Large in size"},
  {"word": "Bin", "clue": "Storage container"},
  {"word": "Bio", "clue": "Short biography"},
  {"word": "Bit", "clue": "Small piece"},
  {"word": "Biz", "clue": "Slang for business"},
  {"word": "Boa", "clue": "Decorative scarf"},
  {"word": "Bob", "clue": "Quick up-and-down move"},
  {"word": "Bod", "clue": "Slang for body"},
  {"word": "Bog", "clue": "Wet, muddy ground"},
  {"word": "Boo", "clue": "Sound of disapproval"},
  {"word": "Bop", "clue": "Dance to pop music"},
  {"word": "Bot", "clue": "Parasitic fly larva"},
  {"word": "Bow", "clue": "Knot with loops"},
  {"word": "Box", "clue": "Square container"},
  {"word": "Boy", "clue": "Young male"},
  {"word": "Bra", "clue": "Women's undergarment"},
  {"word": "Bro", "clue": "Brother, informally"},
  {"word": "Bub", "clue": "Friendly address for a man"},
  {"word": "Bud", "clue": "Undeveloped plant growth"},
  {"word": "Bug", "clue": "Small insect"},
  {"word": "Bum", "clue": "Lazy person"},
  {"word": "Bun", "clue": "Small cake with currants"},
  {"word": "Bur", "clue": "Prickly seed case"},
  {"word": "Bus", "clue": "Public transport vehicle"},
  {"word": "But", "clue": "Contrasting conjunction"},
  {"word": "Buy", "clue": "Purchase with money"},
  {"word": "Bye", "clue": "Free pass in competition"},
  {"word": "Cab", "clue": "Taxi vehicle"},
  {"word": "Cad", "clue": "Dishonorable man"},
  {"word": "Cam", "clue": "Rotating machine part"},
  {"word": "Can", "clue": "Metal container"},
  {"word": "Cap", "clue": "Soft hat with peak"},
  {"word": "Car", "clue": "Four-wheeled vehicle"},
  {"word": "Cat", "clue": "Furry feline pet"},
  {"word": "Caw", "clue": "Crow's harsh cry"},
  {"word": "Cay", "clue": "Coral reef island"},
  {"word": "Cee", "clue": "Letter C"},
  {"word": "Cel", "clue": "Animation transparency"},
  {"word": "Cha", "clue": "Tea, informally"},
  {"word": "Che", "clue": "Argentinian address term"},
  {"word": "Chi", "clue": "Greek letter"},
  {"word": "Cig", "clue": "Cigarette, briefly"},
  {"word": "Cob", "clue": "Maize ear core"},
  {"word": "Cod", "clue": "Large marine fish"},
  {"word": "Cog", "clue": "Toothed wheel part"},
  {"word": "Col", "clue": "Mountain ridge depression"},
  {"word": "Con", "clue": "Deceive with lies"},
  {"word": "Coo", "clue": "Pigeon's soft sound"},
  {"word": "Cop", "clue": "Police officer, slang"},
  {"word": "Cor", "clue": "Exclamation of surprise"},
  {"word": "Cos", "clue": "Type of lettuce"},
  {"word": "Cot", "clue": "Child's barred bed"},
  {"word": "Cow", "clue": "Female bovine"},
  {"word": "Cox", "clue": "Racing boat steerer"},
  {"word": "Coy", "clue": "Pretending shyness"},
  {"word": "Coz", "clue": "Cousin, informally"},
  {"word": "Cru", "clue": "Quality vineyard"},
  {"word": "Cry", "clue": "Shed tears"},
  {"word": "Cub", "clue": "Young lion or bear"},
  {"word": "Cud", "clue": "Ruminant's chewed food"},
  {"word": "Cue", "clue": "Signal for action"},
  {"word": "Cup", "clue": "Drinking vessel"},
  {"word": "Cur", "clue": "Aggressive mongrel dog"},
  {"word": "Cut", "clue": "Slice with a blade"},
  {"word": "Dab", "clue": "Lightly press to clean"},
  {"word": "Dad", "clue": "Father"},
  {"word": "Dag", "clue": "Untidy person"},
  {"word": "Dal", "clue": "Split lentil dish"},
  {"word": "Dam", "clue": "Water-retaining barrier"},
  {"word": "Dan", "clue": "Martial arts level"},
  {"word": "Dap", "clue": "Bob bait on water"},
  {"word": "Daw", "clue": "Jackdaw bird"},
  {"word": "Day", "clue": "24-hour period"},
  {"word": "Deb", "clue": "Young socialite"},
  {"word": "Dee", "clue": "Letter D"},
  {"word": "Def", "clue": "Slang for excellent"},
  {"word": "Del", "clue": "Delegate, briefly"},
  {"word": "Den", "clue": "Animal's lair"},
  {"word": "Dev", "clue": "Software developer"},
  {"word": "Dew", "clue": "Morning condensation"},
  {"word": "Dex", "clue": "Dextroamphetamine tablet"},
  {"word": "Dib", "clue": "Small nondescript object"},
  {"word": "Did", "clue": "Past tense of do"},
  {"word": "Die", "clue": "Cease living"},
  {"word": "Dig", "clue": "Move earth with a tool"},
  {"word": "Dim", "clue": "Faintly lit"},
  {"word": "Din", "clue": "Loud, unpleasant noise"},
  {"word": "Dip", "clue": "Briefly submerge"},
  {"word": "Dis", "clue": "Insult or criticize"},
  {"word": "Doc", "clue": "Doctor, informally"},
  {"word": "Doe", "clue": "Female deer"},
  {"word": "Dog", "clue": "Barking pet"},
  {"word": "Doh", "clue": "First sol-fa note"},
  {"word": "Dol", "clue": "Pain intensity unit"},
  {"word": "Dom", "clue": "Monastic title"},
  {"word": "Don", "clue": "Oxford college teacher"},
  {"word": "Doo", "clue": "Pigeon or dove"},
  {"word": "Dop", "clue": "Small brandy shot"},
  {"word": "Dor", "clue": "Dung beetle"},
  {"word": "Dos", "clue": "Second sol-fa note"},
  {"word": "Dot", "clue": "Small round mark"},
  {"word": "Dow", "clue": "Stock market index"},
  {"word": "Dry", "clue": "Free of moisture"},
  {"word": "Dub", "clue": "Give a nickname"},
  {"word": "Dud", "clue": "Faulty item"},
  {"word": "Due", "clue": "Expected on time"},
  {"word": "Dug", "clue": "Past tense of dig"},
  {"word": "Duh", "clue": "Obviousness exclamation"},
  {"word": "Dum", "clue": "Stupid person"},
  {"word": "Dun", "clue": "Dull brown color"},
  {"word": "Duo", "clue": "Pair of performers"},
  {"word": "Dup", "clue": "Short for duplicate"},
  {"word": "Dye", "clue": "Color-changing substance"},
  {"word": "Ear", "clue": "Hearing organ"},
  {"word": "Eat", "clue": "Consume food"},
  {"word": "Ebb", "clue": "Tide's retreat"},
  {"word": "Eco", "clue": "Environmentally friendly"},
  {"word": "Ecu", "clue": "Old European currency"},
  {"word": "Eek", "clue": "Squeal of alarm"},
  {"word": "Eel", "clue": "Slippery fish"},
  {"word": "Egg", "clue": "Embryo-containing shell"},
  {"word": "Ego", "clue": "Sense of self"},
  {"word": "Eke", "clue": "Use sparingly"},
  {"word": "Elf", "clue": "Mischievous fairy"},
  {"word": "Elk", "clue": "Large antlered deer"},
  {"word": "Elm", "clue": "Deciduous tree"},
  {"word": "Emu", "clue": "Flightless Australian bird"},
  {"word": "End", "clue": "Final point"},
  {"word": "Eng", "clue": "Velar nasal letter"},
  {"word": "Ens", "clue": "Existing entity"},
  {"word": "Eon", "clue": "Vast time period"},
  {"word": "Era", "clue": "Distinct historical period"},
  {"word": "Erg", "clue": "Unit of energy"},
  {"word": "Err", "clue": "Make a mistake"},
  {"word": "Ess", "clue": "Letter S"},
  {"word": "Eta", "clue": "Seventh Greek letter"},
  {"word": "Eth", "clue": "Old English letter"},
  {"word": "Eve", "clue": "Day before an event"},
  {"word": "Ewe", "clue": "Female sheep"},
  {"word": "Eye", "clue": "Vision organ"},
  {"word": "Fab", "clue": "Fabulous or great"},
  {"word": "Fad", "clue": "Short-lived craze"},
  {"word": "Fag", "clue": "Tiring task"},
  {"word": "Fan", "clue": "Cooling device"},
  {"word": "Far", "clue": "Great distance"},
  {"word": "Fat", "clue": "Greasy body substance"},
  {"word": "Fax", "clue": "Electronic document copy"},
  {"word": "Fay", "clue": "Mythical fairy"},
  {"word": "Fed", "clue": "Gave food to"},
  {"word": "Fee", "clue": "Payment for services"},
  {"word": "Fem", "clue": "Female, briefly"},
  {"word": "Fen", "clue": "Marshy land"},
  {"word": "Fer", "clue": "Dialect for 'for'"},
  {"word": "Fet", "clue": "Fetch, briefly"},
  {"word": "Few", "clue": "Small number"},
  {"word": "Fey", "clue": "Unworldly or whimsical"},
  {"word": "Fez", "clue": "Tasseled red hat"},
  {"word": "Fib", "clue": "Small lie"},
  {"word": "Fid", "clue": "Rope-splicing tool"},
  {"word": "Fig", "clue": "Sweet pear-shaped fruit"},
  {"word": "Fil", "clue": "Thread or filament"},
  {"word": "Fin", "clue": "Fish's swimming appendage"},
  {"word": "Fir", "clue": "Evergreen coniferous tree"},
  {"word": "Fit", "clue": "Suitable or healthy"},
  {"word": "Fix", "clue": "Repair or secure"},
  {"word": "Fiz", "clue": "Bubbly sound"},
  {"word": "Flu", "clue": "Influenza illness"},
  {"word": "Fly", "clue": "Move through air"},
  {"word": "Fob", "clue": "Watch chain"},
  {"word": "Foe", "clue": "Enemy"},
  {"word": "Fog", "clue": "Thick atmospheric mist"},
  {"word": "Fon", "clue": "African language"},
  {"word": "Fop", "clue": "Excessively vain man"},
  {"word": "For", "clue": "In support of"},
  {"word": "Fox", "clue": "Cunning canine"},
  {"word": "Foy", "clue": "Farewell gift"},
  {"word": "Fro", "clue": "Away, dialectally"},
  {"word": "Fry", "clue": "Cook in hot oil"},
  {"word": "Fub", "clue": "Cheat or deceive"},
  {"word": "Fud", "clue": "Foolish person"},
  {"word": "Fug", "clue": "Stuffy atmosphere"},
  {"word": "Fun", "clue": "Enjoyment or amusement"},
  {"word": "Fur", "clue": "Animal's soft hair"},
  {"word": "Oaf", "clue": "Clumsy fellow"},
  {"word": "Oak", "clue": "Sturdy tree"},
  {"word": "Oar", "clue": "Rowing tool"},
  {"word": "Oat", "clue": "Cereal grain"},
  {"word": "Odd", "clue": "Not even"},
  {"word": "Ode", "clue": "Poetic tribute"},
  {"word": "Off", "clue": "Deactivate"},
  {"word": "Oft", "clue": "Frequently, poetically"},
  {"word": "Oho", "clue": "Cry of surprise"},
  {"word": "Oil", "clue": "Lubricant liquid"},
  {"word": "Old", "clue": "Aged"},
  {"word": "One", "clue": "Single unit"},
  {"word": "Ooh", "clue": "Sound of awe"},
  {"word": "Ope", "clue": "Open, poetically"},
  {"word": "Opt", "clue": "Choose"},
  {"word": "Orb", "clue": "Spherical object"},
  {"word": "Orc", "clue": "Tolkien's monster"},
  {"word": "Ore", "clue": "Mined material"},
  {"word": "Our", "clue": "Belonging to us"},
  {"word": "Out", "clue": "Not in"},
  {"word": "Ova", "clue": "Eggs in biology"},
  {"word": "Owe", "clue": "Be in debt"},
  {"word": "Owl", "clue": "Night bird"},
  {"word": "Own", "clue": "Possess"},
  {"word": "Pac", "clue": "Shoe insert"},
  {"word": "Pad", "clue": "Cushion or notebook"},
  {"word": "Pal", "clue": "Close friend"},
  {"word": "Pam", "clue": "Nonstick spray brand"},
  {"word": "Pan", "clue": "Cooking vessel"},
  {"word": "Pap", "clue": "Soft food"},
  {"word": "Par", "clue": "Golf standard"},
  {"word": "Pat", "clue": "Gentle touch"},
  {"word": "Paw", "clue": "Animal's foot"},
  {"word": "Pay", "clue": "Compensate"},
  {"word": "Pea", "clue": "Green pod veggie"},
  {"word": "Pec", "clue": "Chest muscle, slangily"},
  {"word": "Ped", "clue": "Foot in anatomy"},
  {"word": "Pee", "clue": "Urinate, informally"},
  {"word": "Peg", "clue": "Wooden pin"},
  {"word": "Pen", "clue": "Writing tool"},
  {"word": "Pep", "clue": "Energy or enthusiasm"},
  {"word": "Per", "clue": "For each"},
  {"word": "Pet", "clue": "Domesticated animal"},
  {"word": "Pew", "clue": "Church bench"},
  {"word": "Pic", "clue": "Photo, slangily"},
  {"word": "Pie", "clue": "Dessert pastry"},
  {"word": "Pig", "clue": "Farm animal"},
  {"word": "Pin", "clue": "Fastener or badge"},
  {"word": "Pip", "clue": "Seed in fruit"},
  {"word": "Pit", "clue": "Fruit stone"},
  {"word": "Pix", "clue": "Photos, slangily"},
  {"word": "Ply", "clue": "Layer or work steadily"},
  {"word": "Pod", "clue": "Seed case"},
  {"word": "Poi", "clue": "Hawaiian taro dish"},
  {"word": "Pol", "clue": "Politician, informally"},
  {"word": "Pop", "clue": "Soda or burst"},
  {"word": "Pot", "clue": "Cooking container"},
  {"word": "Pow", "clue": "Sound of impact"},
  {"word": "Pro", "clue": "Expert"},
  {"word": "Pry", "clue": "Snoop or lever"},
  {"word": "Pub", "clue": "Tavern"},
  {"word": "Pud", "clue": "Pudding, informally"},
  {"word": "Pug", "clue": "Small dog breed"},
  {"word": "Pun", "clue": "Wordplay joke"},
  {"word": "Pup", "clue": "Young dog"},
  {"word": "Pus", "clue": "Infection fluid"},
  {"word": "Put", "clue": "Place or set"},
  {"word": "Qat", "clue": "Stimulant leaf"},
  {"word": "Qua", "clue": "In the capacity of"},
  {"word": "Rad", "clue": "Cool, slangily"},
  {"word": "Rag", "clue": "Tattered cloth"},
  {"word": "Rah", "clue": "Cheerleader's cheer"},
  {"word": "Ram", "clue": "Male sheep"},
  {"word": "Ran", "clue": "Sprinted"},
  {"word": "Rap", "clue": "Knock or music genre"},
  {"word": "Rat", "clue": "Rodent or traitor"},
  {"word": "Raw", "clue": "Uncooked"},
  {"word": "Ray", "clue": "Beam of light"},
  {"word": "Reb", "clue": "Confederate soldier, slangily"},
  {"word": "Rec", "clue": "Recommendation, briefly"},
  {"word": "Red", "clue": "Crimson color"},
  {"word": "Ref", "clue": "Sports official"},
  {"word": "Reg", "clue": "Regulation, shortly"},
  {"word": "Rem", "clue": "Sleep stage"},
  {"word": "Rep", "clue": "Sales agent"},
  {"word": "Rev", "clue": "Increase engine speed"},
  {"word": "Rib", "clue": "Chest bone"},
  {"word": "Rid", "clue": "Free from"},
  {"word": "Rif", "clue": "Layoff, slangily"},
  {"word": "Rig", "clue": "Manipulate or setup"},
  {"word": "Rim", "clue": "Edge of a cup"},
  {"word": "Rin", "clue": "Japanese coin fraction"},
  {"word": "Rip", "clue": "Tear apart"},
  {"word": "Rob", "clue": "Steal from"},
  {"word": "Rod", "clue": "Fishing pole"},
  {"word": "Roe", "clue": "Fish eggs"},
  {"word": "Rot", "clue": "Decay"},
  {"word": "Row", "clue": "Line or paddle"},
  {"word": "Rub", "clue": "Massage or snag"},
  {"word": "Rue", "clue": "Regret"},
  {"word": "Rug", "clue": "Floor covering"},
  {"word": "Rum", "clue": "Pirate's drink"},
  {"word": "Run", "clue": "Jog or manage"},
  {"word": "Rut", "clue": "Groove or habit"},
  {"word": "Rye", "clue": "Whiskey grain"},
  {"word": "Sab", "clue": "Sabotage, briefly"},
  {"word": "Sac", "clue": "Pouch in biology"},
  {"word": "Sad", "clue": "Unhappy"},
  {"word": "Sag", "clue": "Droop"},
  {"word": "Sal", "clue": "Salt, poetically"},
  {"word": "Sam", "clue": "Uncle in America"},
  {"word": "San", "clue": "Japanese honorific"},
  {"word": "Sap", "clue": "Tree fluid"},
  {"word": "Sat", "clue": "Rested on a chair"},
  {"word": "Saw", "clue": "Cutting tool"},
  {"word": "Sax", "clue": "Jazz instrument"},
  {"word": "Say", "clue": "Speak or express"},
  {"word": "Sea", "clue": "Ocean"},
  {"word": "Sec", "clue": "Moment, informally"},
  {"word": "See", "clue": "Observe"},
  {"word": "Seg", "clue": "Segment, briefly"},
  {"word": "Sel", "clue": "French salt"},
  {"word": "Sen", "clue": "Japanese coin"},
  {"word": "Ser", "clue": "Protein fluid"},
  {"word": "Set", "clue": "Place or collection"},
  {"word": "Sew", "clue": "Stitch fabric"},
  {"word": "Sex", "clue": "Gender"},
  {"word": "Sha", "clue": "Hush sound"},
  {"word": "She", "clue": "Female pronoun"},
  {"word": "Shh", "clue": "Be quiet!"},
  {"word": "Sho", "clue": "Sure, dialectally"},
  {"word": "Shy", "clue": "Timid"},
  {"word": "Sib", "clue": "Sibling, briefly"},
  {"word": "Sic", "clue": "As written"},
  {"word": "Sim", "clue": "Phone card"},
  {"word": "Sin", "clue": "Moral wrong"},
  {"word": "Sip", "clue": "Small drink"},
  {"word": "Sir", "clue": "Respectful address"},
  {"word": "Sis", "clue": "Female sibling"},
  {"word": "Sit", "clue": "Take a seat"},
  {"word": "Ska", "clue": "Jamaican music genre"},
  {"word": "Ski", "clue": "Glide on snow"},
  {"word": "Sky", "clue": "Heavens above"},
  {"word": "Sly", "clue": "Cunning"},
  {"word": "Sob", "clue": "Cry heavily"},
  {"word": "Sod", "clue": "Turf or grass"},
  {"word": "Sol", "clue": "Sun or note"},
  {"word": "Son", "clue": "Male child"},
  {"word": "Sop", "clue": "Soak up"},
  {"word": "Sot", "clue": "Drunkard"},
  {"word": "Sou", "clue": "Old French coin"},
  {"word": "Sow", "clue": "Plant seeds"},
  {"word": "Soy", "clue": "Tofu base"},
  {"word": "Spa", "clue": "Relaxation spot"},
  {"word": "Spy", "clue": "Secret agent"},
  {"word": "Sty", "clue": "Pigpen"},
  {"word": "Sub", "clue": "Undersea vessel"},
  {"word": "Sue", "clue": "Take to court"},
  {"word": "Sun", "clue": "Star of the day"},
  {"word": "Sup", "clue": "Dine, slangily"},
  {"word": "Tab", "clue": "Bill at a bar"},
  {"word": "Tad", "clue": "Small amount"},
  {"word": "Tag", "clue": "Label or game"},
  {"word": "Tan", "clue": "Bronze skin"},
  {"word": "Tao", "clue": "Way in philosophy"},
  {"word": "Tap", "clue": "Light knock"},
  {"word": "Tar", "clue": "Road-paving goo"},
  {"word": "Tat", "clue": "Body art, briefly"},
  {"word": "Tau", "clue": "Greek letter"},
  {"word": "Taw", "clue": "Marble in a game"},
  {"word": "Tax", "clue": "Government levy"},
  {"word": "Tea", "clue": "Brewed beverage"},
  {"word": "Ted", "clue": "Spread hay to dry"},
  {"word": "Tee", "clue": "Golf ball stand"},
  {"word": "Ten", "clue": "Decade number"},
  {"word": "Tet", "clue": "Vietnamese New Year"},
  {"word": "The", "clue": "Definite article"},
  {"word": "Tho", "clue": "Though, informally"},
  {"word": "Thy", "clue": "Your, archaically"},
  {"word": "Tic", "clue": "Nervous twitch"},
  {"word": "Tie", "clue": "Knot or draw"},
  {"word": "Til", "clue": "Until, shortened"},
  {"word": "Tin", "clue": "Metal for cans"},
  {"word": "Tip", "clue": "Gratuity"},
  {"word": "Tis", "clue": "It is, poetically"},
  {"word": "Tit", "clue": "Small bird"},
  {"word": "Tod", "clue": "Fox or weight unit"},
  {"word": "Toe", "clue": "Foot digit"},
  {"word": "Tog", "clue": "Dress up, slangily"},
  {"word": "Tom", "clue": "Male cat"},
  {"word": "Ton", "clue": "Weight unit"},
  {"word": "Too", "clue": "Excessively"},
  {"word": "Top", "clue": "Highest point"},
  {"word": "Tor", "clue": "Rocky hill"},
  {"word": "Tot", "clue": "Young child"},
  {"word": "Tow", "clue": "Pull along"},
  {"word": "Toy", "clue": "Plaything"},
  {"word": "Try", "clue": "Attempt"},
  {"word": "Tsk", "clue": "Sound of disapproval"},
  {"word": "Tub", "clue": "Bathing vessel"},
  {"word": "Tug", "clue": "Pull hard"},
  {"word": "Tui", "clue": "New Zealand bird"},
  {"word": "Tun", "clue": "Large cask"},
  {"word": "Tup", "clue": "Ram's mating act"},
  {"word": "Tut", "clue": "Sound of reproach"},
  {"word": "Tux", "clue": "Formal suit, briefly"},
  {"word": "Twa", "clue": "Two, in old Scots"},
  {"word": "Two", "clue": "Pair number"},
  {"word": "Tye", "clue": "Nautical rope"},
  {"word": "Udo", "clue": "Japanese edible plant"},
  {"word": "Ufo", "clue": "Alien craft"},
  {"word": "Ugh", "clue": "Sound of disgust"},
  {"word": "Uke", "clue": "Small guitar"},
  {"word": "Ulu", "clue": "Inuit knife"},
  {"word": "Umm", "clue": "Hesitation sound"},
  {"word": "Ump", "clue": "Baseball official"},
  {"word": "Uns", "clue": "Us, dialectally"},
  {"word": "Upo", "clue": "Upon, poetically"},
  {"word": "Ups", "clue": "Delivery company"},
  {"word": "Urb", "clue": "City, slangily"},
  {"word": "Urd", "clue": "Norse fate goddess"},
  {"word": "Ure", "clue": "River in England"},
  {"word": "Urn", "clue": "Vase for ashes"},
  {"word": "Urp", "clue": "Burp, informally"},
  {"word": "Use", "clue": "Employ"},
  {"word": "Uta", "clue": "Lizard genus"},
  {"word": "Ute", "clue": "Utility vehicle"},
  {"word": "Vac", "clue": "Vacuum cleaner, briefly"},
  {"word": "Van", "clue": "Moving vehicle"},
  {"word": "Var", "clue": "Variable, in coding"},
  {"word": "Vas", "clue": "Anatomical duct"},
  {"word": "Vat", "clue": "Large container"},
  {"word": "Vee", "clue": "Letter V"},
  {"word": "Veg", "clue": "Relax, slangily"},
  {"word": "Vet", "clue": "Animal doctor"},
  {"word": "Vex", "clue": "Annoy"},
  {"word": "Via", "clue": "By way of"},
  {"word": "Vid", "clue": "Video, briefly"},
  {"word": "Vie", "clue": "Compete"},
  {"word": "Vig", "clue": "Bookie's fee"},
  {"word": "Vim", "clue": "Energy"},
  {"word": "Vin", "clue": "Wine, in French"},
  {"word": "Voe", "clue": "Scottish inlet"},
  {"word": "Vow", "clue": "Solemn promise"},
  {"word": "Vox", "clue": "Voice, in Latin"},
  {"word": "Wab", "clue": "Web, dialectally"},
  {"word": "Wad", "clue": "Bundle of cash"},
  {"word": "Wae", "clue": "Woe, in Scots"},
  {"word": "Wag", "clue": "Tail motion"},
  {"word": "Wan", "clue": "Pale"},
  {"word": "Wap", "clue": "Strike quickly"},
  {"word": "War", "clue": "Armed conflict"},
  {"word": "Was", "clue": "Existed in the past"},
  {"word": "Wat", "clue": "Thai temple"},
  {"word": "Waw", "clue": "Arabic letter"},
  {"word": "Wax", "clue": "Candle material"},
  {"word": "Way", "clue": "Path or method"},
  {"word": "Web", "clue": "Spider's creation"},
  {"word": "Wed", "clue": "Marry"},
  {"word": "Wee", "clue": "Very small"},
  {"word": "Wen", "clue": "Skin cyst"},
  {"word": "Wet", "clue": "Soaked"},
  {"word": "Wha", "clue": "Who, in dialect"},
  {"word": "Who", "clue": "Question of identity"},
  {"word": "Why", "clue": "Reason query"},
  {"word": "Wig", "clue": "Hairpiece"},
  {"word": "Win", "clue": "Triumph"},
  {"word": "Wis", "clue": "Know, archaically"},
  {"word": "Wit", "clue": "Clever humor"},
  {"word": "Wiz", "clue": "Expert, slangily"},
  {"word": "Woe", "clue": "Deep sorrow"},
  {"word": "Wog", "clue": "Insect, slangily"},
  {"word": "Wok", "clue": "Stir-fry pan"},
  {"word": "Won", "clue": "South Korean currency"},
  {"word": "Woo", "clue": "Court romantically"},
  {"word": "Wop", "clue": "Hit hard, slangily"},
  {"word": "Wos", "clue": "Woe, in old English"},
  {"word": "Wot", "clue": "Know, in dialect"},
  {"word": "Wow", "clue": "Impress greatly"},
  {"word": "Wry", "clue": "Twisted humor"},
  {"word": "Wud", "clue": "Mad, in Scots"},
  {"word": "Wye", "clue": "Y-shaped junction"},
  {"word": "Wyn", "clue": "Old English rune"},
  {"word": "Yad", "clue": "Torah pointer"},
  {"word": "Yag", "clue": "Synthetic gem"},
  {"word": "Yah", "clue": "Yes, informally"},
  {"word": "Yak", "clue": "Talk endlessly"},
  {"word": "Yam", "clue": "Sweet potato"},
  {"word": "Yap", "clue": "Bark sharply"},
  {"word": "Yar", "clue": "Nimble, nautically"},
  {"word": "Yaw", "clue": "Swerve off course"},
  {"word": "Yay", "clue": "Cheer of joy"},
  {"word": "Yea", "clue": "Affirmative vote"},
  {"word": "Yeh", "clue": "Yeah, casually"},
  {"word": "Yen", "clue": "Japanese currency"},
  {"word": "Yep", "clue": "Informal yes"},
  {"word": "Yes", "clue": "Affirmative"},
  {"word": "Yet", "clue": "Up to now"},
  {"word": "Yew", "clue": "Evergreen tree"},
  {"word": "Yid", "clue": "Yiddish speaker"},
  {"word": "Yin", "clue": "Dark principle in Taoism"},
  {"word": "Yip", "clue": "Puppy's bark"},
  {"word": "Yob", "clue": "Rowdy youth"},
  {"word": "Yod", "clue": "Hebrew letter"},
  {"word": "Yok", "clue": "Laugh, slangily"},
  {"word": "Yom", "clue": "Day in Hebrew"},
  {"word": "Yon", "clue": "Over there, archaically"},
  {"word": "You", "clue": "Second-person pronoun"},
  {"word": "Yow", "clue": "Cry of pain"},
  {"word": "Yuk", "clue": "Laugh or disgust"},
  {"word": "Yum", "clue": "Tasty sound"},
  {"word": "Yup", "clue": "Casual yes"},
  {"word": "Zag", "clue": "Sharp turn"},
  {"word": "Zap", "clue": "Strike with energy"},
  {"word": "Zas", "clue": "Pizzazz, slangily"},
  {"word": "Zax", "clue": "Roofing tool"},
  {"word": "Zed", "clue": "Letter Z"},
  {"word": "Zee", "clue": "American Z"},
  {"word": "Zek", "clue": "Soviet camp prisoner"},
  {"word": "Zen", "clue": "Meditative practice"},
  {"word": "Zep", "clue": "Large sandwich"},
  {"word": "Zho", "clue": "Yak-cattle hybrid"},
  {"word": "Zig", "clue": "Sharp angle turn"},
  {"word": "Zin", "clue": "Red wine, briefly"},
  {"word": "Zip", "clue": "Fastener or speed"},
  {"word": "Zit", "clue": "Pimple, slangily"},
  {"word": "Zoa", "clue": "Colonial organisms"},
  {"word": "Zoo", "clue": "Animal park"},
  {"word": "Aar", "clue": "Swiss river"},
  {"word": "Aby", "clue": "Pay for, archaically"},
  {"word": "Adz", "clue": "Axe-like cutting tool"},
  {"word": "Ain", "clue": "Own, in Scots"},
  {"word": "Ait", "clue": "Small river island"},
  {"word": "Amm", "clue": "Ammunition, briefly"},
  {"word": "Arf", "clue": "Dog's bark sound"},
  {"word": "Auk", "clue": "Diving seabird"},
  {"word": "Awn", "clue": "Grain's bristly projection"},
  {"word": "Axo", "clue": "Axolotl, briefly"},
  {"word": "Eau", "clue": "Water, in French"},
  {"word": "Edd", "clue": "Ocean current swirl"},
  {"word": "Edh", "clue": "Old English letter"},
  {"word": "Eft", "clue": "Young newt"},
  {"word": "Ell", "clue": "Old cloth measure"},
  {"word": "Emo", "clue": "Emotional music genre"},
  {"word": "Eps", "clue": "Greek letter epsilon"},
  {"word": "Ern", "clue": "Sea eagle"},
  {"word": "Ery", "clue": "Heraldic red color"},
  {"word": "Evo", "clue": "Evolution, briefly"},
  {"word": "Ici", "clue": "Here, in French"},
  {"word": "Icy", "clue": "Freezing cold"},
  {"word": "Ids", "clue": "Freudian instincts"},
  {"word": "Ifs", "clue": "Conditions or doubts"},
  {"word": "Ilk", "clue": "Type or sort"},
  {"word": "Ill", "clue": "Sick or unwell"},
  {"word": "Imp", "clue": "Mischievous sprite"},
  {"word": "Ink", "clue": "Writing fluid"},
  {"word": "Inn", "clue": "Traveler's lodging"},
  {"word": "Ion", "clue": "Charged particle"},
  {"word": "Obe", "clue": "West African magic"},
  {"word": "Obi", "clue": "Wide Japanese sash"},
  {"word": "Oca", "clue": "South American tuber"},
  {"word": "Och", "clue": "Scottish exclamation"},
  {"word": "Oda", "clue": "Turkish harem chamber"},
  {"word": "Ods", "clue": "Mild oath, old-fashioned"},
  {"word": "Ohm", "clue": "Electrical resistance unit"},
  {"word": "Ohs", "clue": "Sounds of surprise"},
  {"word": "Oke", "clue": "Okay, informally"},
  {"word": "Ola", "clue": "Spanish wave greeting"},
  {"word": "Oud", "clue": "Middle Eastern lute"},
  {"word": "Uan", "clue": "Young antelope"},
  {"word": "Ulu", "clue": "Inuit knife"},
  {"word": "Uma", "clue": "Hindu goddess"},
  {"word": "Uni", "clue": "University, briefly"},
  {"word": "Ura", "clue": "Japanese sea urchin"},
  {"word": "Uri", "clue": "Swiss canton"},
  {"word": "Uta", "clue": "Lizard genus"},
  {"word": "Ute", "clue": "Utility vehicle"},
  {"word": "Uva", "clue": "Grape, in Latin"},
  {"word": "Uzi", "clue": "Israeli submachine gun"}
]