const words = [
    {"word": "Oaf", "clue": "Clumsy fellow"},
    {"word": "Oak", "clue": "Sturdy tree"},
    {"word": "Oar", "clue": "Rowing tool"},
    {"word": "Oat", "clue": "Cereal grain"},
    {"word": "Odd", "clue": "Not even"},
    {"word": "Ode", "clue": "Poetic tribute"},
    {"word": "Off", "clue": "Deactivate"},
    {"word": "Oft", "clue": "Frequently, poetically"},
    {"word": "Oho", "clue": "Cry of surprise"},
    {"word": "Oil", "clue": "Lubricant liquid"},
    {"word": "Old", "clue": "Aged"},
    {"word": "One", "clue": "Single unit"},
    {"word": "Ooh", "clue": "Sound of awe"},
    {"word": "Ope", "clue": "Open, poetically"},
    {"word": "Opt", "clue": "Choose"},
    {"word": "Orb", "clue": "Spherical object"},
    {"word": "Orc", "clue": "Tolkien's monster"},
    {"word": "Ore", "clue": "Mined material"},
    {"word": "Our", "clue": "Belonging to us"},
    {"word": "Out", "clue": "Not in"},
    {"word": "Ova", "clue": "Eggs in biology"},
    {"word": "Owe", "clue": "Be in debt"},
    {"word": "Owl", "clue": "Night bird"},
    {"word": "Own", "clue": "Possess"},
    {"word": "Pac", "clue": "Shoe insert"},
    {"word": "Pad", "clue": "Cushion or notebook"},
    {"word": "Pal", "clue": "Close friend"},
    {"word": "Pam", "clue": "Nonstick spray brand"},
    {"word": "Pan", "clue": "Cooking vessel"},
    {"word": "Pap", "clue": "Soft food"},
    {"word": "Par", "clue": "Golf standard"},
    {"word": "Pat", "clue": "Gentle touch"},
    {"word": "Paw", "clue": "Animal's foot"},
    {"word": "Pay", "clue": "Compensate"},
    {"word": "Pea", "clue": "Green pod veggie"},
    {"word": "Pec", "clue": "Chest muscle, slangily"},
    {"word": "Ped", "clue": "Foot in anatomy"},
    {"word": "Pee", "clue": "Urinate, informally"},
    {"word": "Peg", "clue": "Wooden pin"},
    {"word": "Pen", "clue": "Writing tool"},
    {"word": "Pep", "clue": "Energy or enthusiasm"},
    {"word": "Per", "clue": "For each"},
    {"word": "Pet", "clue": "Domesticated animal"},
    {"word": "Pew", "clue": "Church bench"},
    {"word": "Pic", "clue": "Photo, slangily"},
    {"word": "Pie", "clue": "Dessert pastry"},
    {"word": "Pig", "clue": "Farm animal"},
    {"word": "Pin", "clue": "Fastener or badge"},
    {"word": "Pip", "clue": "Seed in fruit"},
    {"word": "Pit", "clue": "Fruit stone"},
    {"word": "Pix", "clue": "Photos, slangily"},
    {"word": "Ply", "clue": "Layer or work steadily"},
    {"word": "Pod", "clue": "Seed case"},
    {"word": "Poi", "clue": "Hawaiian taro dish"},
    {"word": "Pol", "clue": "Politician, informally"},
    {"word": "Pop", "clue": "Soda or burst"},
    {"word": "Pot", "clue": "Cooking container"},
    {"word": "Pow", "clue": "Sound of impact"},
    {"word": "Pro", "clue": "Expert"},
    {"word": "Pry", "clue": "Snoop or lever"},
    {"word": "Pub", "clue": "Tavern"},
    {"word": "Pud", "clue": "Pudding, informally"},
    {"word": "Pug", "clue": "Small dog breed"},
    {"word": "Pun", "clue": "Wordplay joke"},
    {"word": "Pup", "clue": "Young dog"},
    {"word": "Pus", "clue": "Infection fluid"},
    {"word": "Put", "clue": "Place or set"},
    {"word": "Qat", "clue": "Stimulant leaf"},
    {"word": "Qua", "clue": "In the capacity of"},
    {"word": "Rad", "clue": "Cool, slangily"},
    {"word": "Rag", "clue": "Tattered cloth"},
    {"word": "Rah", "clue": "Cheerleader's cheer"},
    {"word": "Ram", "clue": "Male sheep"},
    {"word": "Ran", "clue": "Sprinted"},
    {"word": "Rap", "clue": "Knock or music genre"},
    {"word": "Rat", "clue": "Rodent or traitor"},
    {"word": "Raw", "clue": "Uncooked"},
    {"word": "Ray", "clue": "Beam of light"},
    {"word": "Reb", "clue": "Confederate soldier, slangily"},
    {"word": "Rec", "clue": "Recommendation, briefly"},
    {"word": "Red", "clue": "Crimson color"},
    {"word": "Ref", "clue": "Sports official"},
    {"word": "Reg", "clue": "Regulation, shortly"},
    {"word": "Rem", "clue": "Sleep stage"},
    {"word": "Rep", "clue": "Sales agent"},
    {"word": "Rev", "clue": "Increase engine speed"},
    {"word": "Rib", "clue": "Chest bone"},
    {"word": "Rid", "clue": "Free from"},
    {"word": "Rif", "clue": "Layoff, slangily"},
    {"word": "Rig", "clue": "Manipulate or setup"},
    {"word": "Rim", "clue": "Edge of a cup"},
    {"word": "Rin", "clue": "Japanese coin fraction"},
    {"word": "Rip", "clue": "Tear apart"},
    {"word": "Rob", "clue": "Steal from"},
    {"word": "Rod", "clue": "Fishing pole"},
    {"word": "Roe", "clue": "Fish eggs"},
    {"word": "Rot", "clue": "Decay"},
    {"word": "Row", "clue": "Line or paddle"},
    {"word": "Rub", "clue": "Massage or snag"},
    {"word": "Rue", "clue": "Regret"},
    {"word": "Rug", "clue": "Floor covering"},
    {"word": "Rum", "clue": "Pirate's drink"},
    {"word": "Run", "clue": "Jog or manage"},
    {"word": "Rut", "clue": "Groove or habit"},
    {"word": "Rye", "clue": "Whiskey grain"},
    {"word": "Sab", "clue": "Sabotage, briefly"},
    {"word": "Sac", "clue": "Pouch in biology"},
    {"word": "Sad", "clue": "Unhappy"},
    {"word": "Sag", "clue": "Droop"},
    {"word": "Sal", "clue": "Salt, poetically"},
    {"word": "Sam", "clue": "Uncle in America"},
    {"word": "San", "clue": "Japanese honorific"},
    {"word": "Sap", "clue": "Tree fluid"},
    {"word": "Sat", "clue": "Rested on a chair"},
    {"word": "Saw", "clue": "Cutting tool"},
    {"word": "Sax", "clue": "Jazz instrument"},
    {"word": "Say", "clue": "Speak or express"},
    {"word": "Sea", "clue": "Ocean"},
    {"word": "Sec", "clue": "Moment, informally"},
    {"word": "See", "clue": "Observe"},
    {"word": "Seg", "clue": "Segment, briefly"},
    {"word": "Sel", "clue": "French salt"},
    {"word": "Sen", "clue": "Japanese coin"},
    {"word": "Ser", "clue": "Protein fluid"},
    {"word": "Set", "clue": "Place or collection"},
    {"word": "Sew", "clue": "Stitch fabric"},
    {"word": "Sex", "clue": "Gender"},
    {"word": "Sha", "clue": "Hush sound"},
    {"word": "She", "clue": "Female pronoun"},
    {"word": "Shh", "clue": "Be quiet!"},
    {"word": "Sho", "clue": "Sure, dialectally"},
    {"word": "Shy", "clue": "Timid"},
    {"word": "Sib", "clue": "Sibling, briefly"},
    {"word": "Sic", "clue": "As written"},
    {"word": "Sim", "clue": "Phone card"},
    {"word": "Sin", "clue": "Moral wrong"},
    {"word": "Sip", "clue": "Small drink"},
    {"word": "Sir", "clue": "Respectful address"},
    {"word": "Sis", "clue": "Female sibling"},
    {"word": "Sit", "clue": "Take a seat"},
    {"word": "Ska", "clue": "Jamaican music genre"},
    {"word": "Ski", "clue": "Glide on snow"},
    {"word": "Sky", "clue": "Heavens above"},
    {"word": "Sly", "clue": "Cunning"},
    {"word": "Sob", "clue": "Cry heavily"},
    {"word": "Sod", "clue": "Turf or grass"},
    {"word": "Sol", "clue": "Sun or note"},
    {"word": "Son", "clue": "Male child"},
    {"word": "Sop", "clue": "Soak up"},
    {"word": "Sot", "clue": "Drunkard"},
    {"word": "Sou", "clue": "Old French coin"},
    {"word": "Sow", "clue": "Plant seeds"},
    {"word": "Soy", "clue": "Tofu base"},
    {"word": "Spa", "clue": "Relaxation spot"},
    {"word": "Spy", "clue": "Secret agent"},
    {"word": "Sty", "clue": "Pigpen"},
    {"word": "Sub", "clue": "Undersea vessel"},
    {"word": "Sue", "clue": "Take to court"},
    {"word": "Sun", "clue": "Star of the day"},
    {"word": "Sup", "clue": "Dine, slangily"},
    {"word": "Tab", "clue": "Bill at a bar"},
    {"word": "Tad", "clue": "Small amount"},
    {"word": "Tag", "clue": "Label or game"},
    {"word": "Tan", "clue": "Bronze skin"},
    {"word": "Tao", "clue": "Way in philosophy"},
    {"word": "Tap", "clue": "Light knock"},
    {"word": "Tar", "clue": "Road-paving goo"},
    {"word": "Tat", "clue": "Body art, briefly"},
    {"word": "Tau", "clue": "Greek letter"},
    {"word": "Taw", "clue": "Marble in a game"},
    {"word": "Tax", "clue": "Government levy"},
    {"word": "Tea", "clue": "Brewed beverage"},
    {"word": "Ted", "clue": "Spread hay to dry"},
    {"word": "Tee", "clue": "Golf ball stand"},
    {"word": "Ten", "clue": "Decade number"},
    {"word": "Tet", "clue": "Vietnamese New Year"},
    {"word": "The", "clue": "Definite article"},
    {"word": "Tho", "clue": "Though, informally"},
    {"word": "Thy", "clue": "Your, archaically"},
    {"word": "Tic", "clue": "Nervous twitch"},
    {"word": "Tie", "clue": "Knot or draw"},
    {"word": "Til", "clue": "Until, shortened"},
    {"word": "Tin", "clue": "Metal for cans"},
    {"word": "Tip", "clue": "Gratuity"},
    {"word": "Tis", "clue": "It is, poetically"},
    {"word": "Tit", "clue": "Small bird"},
    {"word": "Tod", "clue": "Fox or weight unit"},
    {"word": "Toe", "clue": "Foot digit"},
    {"word": "Tog", "clue": "Dress up, slangily"},
    {"word": "Tom", "clue": "Male cat"},
    {"word": "Ton", "clue": "Weight unit"},
    {"word": "Too", "clue": "Excessively"},
    {"word": "Top", "clue": "Highest point"},
    {"word": "Tor", "clue": "Rocky hill"},
    {"word": "Tot", "clue": "Young child"},
    {"word": "Tow", "clue": "Pull along"},
    {"word": "Toy", "clue": "Plaything"},
    {"word": "Try", "clue": "Attempt"},
    {"word": "Tsk", "clue": "Sound of disapproval"},
    {"word": "Tub", "clue": "Bathing vessel"},
    {"word": "Tug", "clue": "Pull hard"},
    {"word": "Tui", "clue": "New Zealand bird"},
    {"word": "Tun", "clue": "Large cask"},
    {"word": "Tup", "clue": "Ram's mating act"},
    {"word": "Tut", "clue": "Sound of reproach"},
    {"word": "Tux", "clue": "Formal suit, briefly"},
    {"word": "Twa", "clue": "Two, in old Scots"},
    {"word": "Two", "clue": "Pair number"},
    {"word": "Tye", "clue": "Nautical rope"},
    {"word": "Udo", "clue": "Japanese edible plant"},
    {"word": "Ufo", "clue": "Alien craft"},
    {"word": "Ugh", "clue": "Sound of disgust"},
    {"word": "Uke", "clue": "Small guitar"},
    {"word": "Ulu", "clue": "Inuit knife"},
    {"word": "Umm", "clue": "Hesitation sound"},
    {"word": "Ump", "clue": "Baseball official"},
    {"word": "Uns", "clue": "Us, dialectally"},
    {"word": "Upo", "clue": "Upon, poetically"},
    {"word": "Ups", "clue": "Delivery company"},
    {"word": "Urb", "clue": "City, slangily"},
    {"word": "Urd", "clue": "Norse fate goddess"},
    {"word": "Ure", "clue": "River in England"},
    {"word": "Urn", "clue": "Vase for ashes"},
    {"word": "Urp", "clue": "Burp, informally"},
    {"word": "Use", "clue": "Employ"},
    {"word": "Uta", "clue": "Lizard genus"},
    {"word": "Ute", "clue": "Utility vehicle"},
    {"word": "Vac", "clue": "Vacuum cleaner, briefly"},
    {"word": "Van", "clue": "Moving vehicle"},
    {"word": "Var", "clue": "Variable, in coding"},
    {"word": "Vas", "clue": "Anatomical duct"},
    {"word": "Vat", "clue": "Large container"},
    {"word": "Vee", "clue": "Letter V"},
    {"word": "Veg", "clue": "Relax, slangily"},
    {"word": "Vet", "clue": "Animal doctor"},
    {"word": "Vex", "clue": "Annoy"},
    {"word": "Via", "clue": "By way of"},
    {"word": "Vid", "clue": "Video, briefly"},
    {"word": "Vie", "clue": "Compete"},
    {"word": "Vig", "clue": "Bookie's fee"},
    {"word": "Vim", "clue": "Energy"},
    {"word": "Vin", "clue": "Wine, in French"},
    {"word": "Voe", "clue": "Scottish inlet"},
    {"word": "Vow", "clue": "Solemn promise"},
    {"word": "Vox", "clue": "Voice, in Latin"},
    {"word": "Wab", "clue": "Web, dialectally"},
    {"word": "Wad", "clue": "Bundle of cash"},
    {"word": "Wae", "clue": "Woe, in Scots"},
    {"word": "Wag", "clue": "Tail motion"},
    {"word": "Wan", "clue": "Pale"},
    {"word": "Wap", "clue": "Strike quickly"},
    {"word": "War", "clue": "Armed conflict"},
    {"word": "Was", "clue": "Existed in the past"},
    {"word": "Wat", "clue": "Thai temple"},
    {"word": "Waw", "clue": "Arabic letter"},
    {"word": "Wax", "clue": "Candle material"},
    {"word": "Way", "clue": "Path or method"},
    {"word": "Web", "clue": "Spider's creation"},
    {"word": "Wed", "clue": "Marry"},
    {"word": "Wee", "clue": "Very small"},
    {"word": "Wen", "clue": "Skin cyst"},
    {"word": "Wet", "clue": "Soaked"},
    {"word": "Wha", "clue": "Who, in dialect"},
    {"word": "Who", "clue": "Question of identity"},
    {"word": "Why", "clue": "Reason query"},
    {"word": "Wig", "clue": "Hairpiece"},
    {"word": "Win", "clue": "Triumph"},
    {"word": "Wis", "clue": "Know, archaically"},
    {"word": "Wit", "clue": "Clever humor"},
    {"word": "Wiz", "clue": "Expert, slangily"},
    {"word": "Woe", "clue": "Deep sorrow"},
    {"word": "Wog", "clue": "Insect, slangily"},
    {"word": "Wok", "clue": "Stir-fry pan"},
    {"word": "Won", "clue": "South Korean currency"},
    {"word": "Woo", "clue": "Court romantically"},
    {"word": "Wop", "clue": "Hit hard, slangily"},
    {"word": "Wos", "clue": "Woe, in old English"},
    {"word": "Wot", "clue": "Know, in dialect"},
    {"word": "Wow", "clue": "Impress greatly"},
    {"word": "Wry", "clue": "Twisted humor"},
    {"word": "Wud", "clue": "Mad, in Scots"},
    {"word": "Wye", "clue": "Y-shaped junction"},
    {"word": "Wyn", "clue": "Old English rune"},
    {"word": "Yad", "clue": "Torah pointer"},
    {"word": "Yag", "clue": "Synthetic gem"},
    {"word": "Yah", "clue": "Yes, informally"},
    {"word": "Yak", "clue": "Talk endlessly"},
    {"word": "Yam", "clue": "Sweet potato"},
    {"word": "Yap", "clue": "Bark sharply"},
    {"word": "Yar", "clue": "Nimble, nautically"},
    {"word": "Yaw", "clue": "Swerve off course"},
    {"word": "Yay", "clue": "Cheer of joy"},
    {"word": "Yea", "clue": "Affirmative vote"},
    {"word": "Yeh", "clue": "Yeah, casually"},
    {"word": "Yen", "clue": "Japanese currency"},
    {"word": "Yep", "clue": "Informal yes"},
    {"word": "Yes", "clue": "Affirmative"},
    {"word": "Yet", "clue": "Up to now"},
    {"word": "Yew", "clue": "Evergreen tree"},
    {"word": "Yid", "clue": "Yiddish speaker"},
    {"word": "Yin", "clue": "Dark principle in Taoism"},
    {"word": "Yip", "clue": "Puppy's bark"},
    {"word": "Yob", "clue": "Rowdy youth"},
    {"word": "Yod", "clue": "Hebrew letter"},
    {"word": "Yok", "clue": "Laugh, slangily"},
    {"word": "Yom", "clue": "Day in Hebrew"},
    {"word": "Yon", "clue": "Over there, archaically"},
    {"word": "You", "clue": "Second-person pronoun"},
    {"word": "Yow", "clue": "Cry of pain"},
    {"word": "Yuk", "clue": "Laugh or disgust"},
    {"word": "Yum", "clue": "Tasty sound"},
    {"word": "Yup", "clue": "Casual yes"},
    {"word": "Zag", "clue": "Sharp turn"},
    {"word": "Zap", "clue": "Strike with energy"},
    {"word": "Zas", "clue": "Pizzazz, slangily"},
    {"word": "Zax", "clue": "Roofing tool"},
    {"word": "Zed", "clue": "Letter Z"},
    {"word": "Zee", "clue": "American Z"},
    {"word": "Zek", "clue": "Soviet camp prisoner"},
    {"word": "Zen", "clue": "Meditative practice"},
    {"word": "Zep", "clue": "Large sandwich"},
    {"word": "Zho", "clue": "Yak-cattle hybrid"},
    {"word": "Zig", "clue": "Sharp angle turn"},
    {"word": "Zin", "clue": "Red wine, briefly"},
    {"word": "Zip", "clue": "Fastener or speed"},
    {"word": "Zit", "clue": "Pimple, slangily"},
    {"word": "Zoa", "clue": "Colonial organisms"},
    {"word": "Zoo", "clue": "Animal park"}
  ]