const words = [
    { word: "WAHA", translation: "Mouth" },
    { word: "ARERO", translation: "Tongue" },
    { word: "RINGA", translation: "Hand" },
    { word: "IHU", translation: "Nose" },
    { word: "RINGARINGA", translation: "Hands" },
    { word: "WAEWAE", translation: "Feet" },
    { word: "UPOKO", translation: "Head" },
    { word: "MAIKUKU", translation: "Fingernail Toenail" },
    { word: "WAEWAERARO", translation: "Legs" },
    { word: "TARINGA", translation: "Ear" },
    { word: "HOPE", translation: "Waist" },
    { word: "TURI", translation: "Knee" },
    { word: "KARU", translation: "Eye" },
    { word: "KAKĪ", translation: "Neck" },
    { word: "MATIMATI", translation: "Fingers" },
    { word: "TUARĀ", translation: "Back" },
    { word: "POKOHIWI", translation: "Shoulder" },
    { word: "PUKU", translation: "Stomach" },
    { word: "KANOHI", translation: "Face" },
    { word: "NIHO", translation: "Teeth" },
    { word: "HAERENGA", translation: "Journey" },
    { word: "ĀKUANEI", translation: "Soon, presently" },
    { word: "ĀTAHIRĀ", translation: "Morning, dawn" },
    { word: "TĀKARO", translation: "Play, game" },
    { word: "TĪMATA", translation: "Begin, start" },
    { word: "TĀMAKI", translation: "Battle, fight (also a place name, e.g., Tāmaki Makaurau for Auckland)" },
    { word: "MARAMA", translation: "Month, moon, clear, understand" },
    { word: "TĒTAHI", translation: "One, a certain, some" },
    { word: "HAERE", translation: "Go, leave, proceed" },
    { word: "MĀTOU", translation: "We (exclusive, including the speaker but not the person spoken to)" },
    { word: "ĀPŌPŌ", translation: "Tomorrow" },
    { word: "RĀTOU", translation: "They (three or more, excluding the speaker and listener)" },
    { word: "WHARE", translation: "House, building" },
    { word: "TAONE", translation: "Town, city" },
    { word: "WIKI", translation: "Week" },
    { word: "TĒRĀ", translation: "That, those (over there)" },
    { word: "KURA", translation: "School, red" },
    { word: "NEKE", translation: "Move, shift" },
    { word: "HEKE", translation: "Descend, migrate" },
    { word: "TIPU", translation: "Grow, increase" },
    { word: "AROHA", translation: "Love" },
    { word: "KAI", translation: "Food" },
    { word: "WAI", translation: "Water" },
    { word: "TĒNĀKOE", translation: "Hello (to one person)" },
    { word: "HAEREMAI", translation: "Welcome" },
    { word: "KIAORA", translation: "Hello, thank you, be well" },
    { word: "WHĀNAU", translation: "Family" },
    { word: "HĀNGI", translation: "Traditional Māori earth oven" },
    { word: "MAHI", translation: "Work, activity" },
    { word: "AOTEAROA", translation: "New Zealand (land of the long white cloud)" },
    { word: "PŌWHIRI", translation: "Formal welcome ceremony" },
    { word: "MĀORI", translation: "Indigenous people of New Zealand" },
    { word: "MANUHIRI", translation: "Guests, visitors" },
    { word: "KŌRERO", translation: "Talk, speak, speech" },
    { word: "HAKA", translation: "Traditional Māori war dance or challenge" },
    { word: "MARAE", translation: "Traditional Māori meeting grounds" },
    { word: "TAMARIKI", translation: "Children" },
    { word: "WAKA", translation: "Canoe, vehicle" },
    { word: "TĒNĀKOUTOU", translation: "Hello (to three or more people)" }
];
